/**
 * Phase 10i.0-LP.7 — recipe-playbook synthesis test.
 *
 * The durable guarantee that the LP architecture is *truly* pack-driven.
 *
 * Defines a synthetic pack (`mockPlaybookPack`) implementing every
 * `LanguageSupport` field, mocks the registry to include it, and asserts
 * each pack-iterating consumer picks up its contributions. If a future PR
 * re-introduces hardcoded language coupling — even subtly, even in a
 * consumer not yet known to the LP audit — this test fails.
 *
 * What's covered (LP.1 through LP.6 deliverables):
 *   - allSourceExtensions / allTestFilePatterns iterate the registry
 *   - DEFAULT_VERSIONS pulls each pack's defaultVersion
 *   - buildVariables emits <KEY>_VERSION for every pack
 *   - buildConditions emits IF_<KEY> for every pack
 *   - activeLanguagesFromFlags activates a pack when its versionKey flag
 *     is true in the stack (LP.7 made this pack-driven)
 *   - buildRequiredTools concatenates active packs' tools
 *   - detect() iterates LANGUAGES and calls each pack's .detect(cwd)
 *
 * Synthetic-id choice (`'playbook'`):
 *   The mock uses an id deliberately outside the `LanguageId` union so it
 *   never collides with a real pack. Phase 10j.1 (Kotlin) surfaced this:
 *   the original mock used `'kotlin'` as a placeholder, then collided
 *   when the real Kotlin pack landed. The lesson generalised — synthetic
 *   ids should be unmistakably non-language (`playbook`) so this test
 *   keeps working as future packs are added without further renames.
 *
 * Post-10f.4 note:
 *   `DetectedStack.languages` is now `Record<LanguageId, boolean>`. The
 *   synthetic pack's id is not in the union, so the test casts the
 *   stack/flags object via `as any` to inject the synthetic flag. Real
 *   packs don't need any cast.
 */

import { describe, it, expect, vi, beforeAll, afterAll } from 'vitest';
import type { LanguageSupport } from '../src/languages';
import {
  LANGUAGES,
  allAutogenSourcePatterns,
  allDependencyManifestPatterns,
  changedFilesTouchDependencyManifest,
  allDocCommentPatterns,
  allExportDetectionDeclarations,
  allFlowSourceExtensions,
  allModelSchema,
  allModelSchemaSourceExtensions,
  changedFilesTouchModelSurface,
  allCiSetupSteps,
  allHttpFlow,
  allModelPaths,
  changedFilesTouchFlowSurface,
  allPrimaryComponentPaths,
  allRoutePaths,
  allSourceExtensions,
  allTestFilePatterns,
  allTestGapPriorityPaths,
  allTlsBypassPatterns,
  activeLanguagesFromFlags,
  activeLanguagesFromStack,
  activeCorrectnessProviders,
  activeLintGateProviders,
  buildDevcontainerExtensions,
  buildDevcontainerFeatures,
  detectActiveLanguages,
  dominantVocabulary,
} from '../src/languages';
import { runCorrectnessFloor } from '../src/analyzers/correctness/run';
import { lintGateSpecs } from '../src/analyzers/custom-checks/config';
import { deriveFileRoutePath } from '../src/analyzers/flow/file-routes';
import { extractFromTree } from '../src/analyzers/flow/extract';
import { parseSource } from '../src/ast/parse';
import { grammarShape } from '../src/ast/grammar-shape';
import { modelShapeForGrammar } from '../src/ast/grammar-model-shape';
import { extractModelsFromTree } from '../src/analyzers/model-schema/extract';
import { buildVariables, buildConditions } from '../src/constants';
import { buildRequiredTools } from '../src/analyzers/tools/tool-registry';
import { detect } from '../src/detect';
import * as fs from 'fs';
import * as os from 'os';
import { gatherPackDepVulnsAcrossRoots } from '../src/analyzers/security/gather';
import { clearWalkPathsCache } from '../src/analyzers/tools/walk-paths';
import * as path from 'path';

// ─── The mock synthetic pack ────────────────────────────────────────────────
// Distinctive extensions/patterns/binaries (`.pbk`, `playbookc-mock`) so the
// assertions verify the *synthetic* contributions specifically, never
// accidentally satisfied by a real pack that happens to share a token.
const mockPlaybookPack = {
  id: 'playbook',
  displayName: 'Playbook (synthetic — recipe playbook)',
  sourceExtensions: ['.pbk', '.pbkx'],
  testFilePatterns: ['*Test.pbk', 'src/test/playbook/*.pbk'],
  extraExcludes: ['playbook-build', '.playbook-cache'],
  autogeneratedSourcePatterns: ['*.designer.pbk', '*.g.pbk'],
  docCommentPatterns: ['^playbook-doc:'],
  tlsBypassPatterns: ['PlaybookInsecureTransport'],
  // Distinctive strategy string so the assertion verifies the synthetic
  // pack's contribution specifically, never accidentally satisfied by a
  // real pack that happens to share a token.
  exportDetection: {
    reliability: 'partial' as const,
    strategy: 'playbook-mock-export-strategy: detect via @playbook-export annotation',
  },
  // Architectural-shape contribution. Distinctive path tokens
  // (`/playbookplane/`, `/playbookbinder/`, `/playbookforms/`,
  // `/playbookmodels/`, `/playbookroutes/`) so assertions verify
  // the synthetic pack's paths specifically — never accidentally
  // satisfied by a real pack that shares a token.
  architecturalShape: {
    primaryComponentPaths: ['/playbookplane/', '/playbookbinder/', '/playbookforms/'],
    routePaths: ['/playbookroutes/'],
    modelPaths: ['/playbookmodels/'],
    vocabulary: {
      components: 'playbook-planes',
      models: 'playbook-models',
      routes: 'playbook-routes',
    },
    testGapPriority: {
      critical: ['/playbookauth/'],
      high: ['/playbookplane/'],
      medium: ['/playbookbinder/', '/playbookforms/'],
    },
  },
  // CI runtime-setup contribution (2.32). Distinctive action ref + version so
  // the assertion verifies the synthetic pack's ciSetup flows through
  // `allCiSetupSteps` into the workflow — codifying "CI runtime setup is
  // pack-driven, not a Node-only hardcode."
  ciSetup: {
    steps: [
      {
        name: 'Set up Playbook',
        uses: 'playbook/setup-playbook@v9',
        with: { 'playbook-version': '9.9.9' },
        // `versionInput` + `detectVersion` below prove version DERIVATION is
        // pack-driven: `allCiSetupSteps(flags, cwd)` must substitute the
        // synthetic pack's DETECTED version (42.0.0) here, not the default.
        versionInput: 'playbook-version',
      },
    ],
  },
  detectVersion: () => '42.0.0',
  // HTTP-flow contribution. Distinctive tokens (`playbookFetch`,
  // `playbookClient`, `playbookGet`, `playbookApp`) so the assertion verifies
  // the synthetic pack's httpFlow descriptor flows through `allHttpFlow` —
  // codifying "flow extraction is pack-driven, not analyzer-by-analyzer."
  httpFlow: {
    clientCallees: ['playbookFetch'],
    clientMethodCallees: { methods: ['playbookGet'], bases: ['playbookClient'] },
    routeDecorators: ['playbookGet'],
    routeRouterCallees: { methods: ['playbookGet'], bases: ['playbookApp'] },
    // Non-verb tokens NEED an alias to mint a method — the end-to-end
    // extraction test below is what proves the alias map flows through.
    // Keys are LOWERCASE method tokens (normalizeMethod lowercases before
    // lookup) — this fixture originally used camelCase keys, which the
    // registry-presence assertion could not catch; the extraction test can.
    methodAliases: { playbookdel: 'DELETE', playbookget: 'GET' },
    // File-convention routing (2.28): distinctive tokens so the assertion
    // verifies the synthetic pack's fileRoutes descriptor drives the SHARED
    // path algebra (`deriveFileRoutePath`) — codifying "file-route derivation
    // is pack-driven, not hardcoded to Next.js's `route`/`app` names."
    fileRoutes: {
      handlerFile: 'playbookroute',
      baseDirs: ['playbookapp'],
      methodExports: ['GET', 'POST'],
    },
  },
  // Model-schema contribution. Distinctive tokens (`PlaybookRecord`,
  // `PlaybookEntity`, `playbookColumn`) so the assertions verify the
  // synthetic pack's modelSchema descriptor flows through `allModelSchema`
  // AND drives the ONE model extractor — codifying "model extraction is
  // pack-driven, not analyzer-by-analyzer."
  modelSchema: {
    modelBaseClasses: ['PlaybookRecord'],
    modelDecorators: ['PlaybookEntity'],
    fieldCallees: [{ names: ['playbookColumn'], optionalityKeyword: 'playbookNullable' }],
    typeAliases: { playbookcolumn: 'playbook-string' },
    schemaSignals: [{ manifest: 'playbook.toml', anyOf: ['playbook-orm'] }],
  },
  // A grammar alongside httpFlow makes the synthetic pack flow-CAPABLE, so its
  // extensions flow through `allFlowSourceExtensions` /
  // `changedFilesTouchFlowSurface` — codifying "the flow-gate trigger is
  // pack-driven, not a hardcoded extension list."
  treeSitterGrammars: { '.pbk': 'playbook-lang' },
  // Correctness-floor contribution (2.23). Distinctive bin/labels so the
  // assertion verifies the synthetic pack's provider flows through
  // `activeCorrectnessProviders` + `runCorrectnessFloor` — codifying "the
  // liveness floor is pack-driven, not analyzer-by-analyzer."
  correctness: {
    syntaxCheck: () => ({ label: 'playbook-typecheck', bin: 'playbookc-mock', args: ['--check'] }),
    affectedTests: () => ({ label: 'playbook-tests', bin: 'playbookc-mock', args: ['test'] }),
  },
  // Lint-GATE contribution (custom-check flagship). Distinctive bin/parse so the
  // assertion verifies the synthetic pack's provider flows through
  // `activeLintGateProviders` + `lintGateSpecs` — codifying "the lint gate is
  // pack-driven, a consumer of the one custom-check runner seam."
  lintGate: {
    lintCommand: () => ({
      bin: 'playbook-lint-mock',
      args: ['--gate'],
      parse: '^(?<file>[^:]+):(?<line>\\d+):\\s+(?<rule>\\w+)\\s+(?<message>.*)$',
      expectedExit: 0,
    }),
  },
  detect: vi.fn(() => false),
  tools: [],
  semgrepRulesets: [],
  capabilities: {
    coverage: {
      source: 'playbook-mock',
      async gather() {
        return null;
      },
    },
    // Distinctive manifest patterns so the assertion verifies the synthetic
    // pack's dependency-manifest contribution flows through the registry
    // helpers that drive the incremental dep-audit skip (2.16).
    depVulns: {
      source: 'playbook-mock',
      manifestPatterns: ['playbook.lock', '*.pbkproj'],
      // Distinctive lockfile basename so the nested-root dispatch assertion
      // below proves per-root auditing is declaration-driven.
      lockfilePatterns: ['playbook.lock'],
      async gather() {
        return null;
      },
      async gatherOutcome() {
        return { kind: 'no-manifest', reason: 'mock' };
      },
    },
  },
  permissions: ['Bash(mock-playbook-permission:*)'],
  ruleFile: 'playbook-mock.md',
  cliBinaries: ['playbookc-mock'],
  defaultVersion: '99.0.0',
  versionKey: 'playbook',
  // Distinctive feature name so the assertion verifies the synthetic
  // pack's contribution specifically, never accidentally satisfied by
  // a real pack that shares a feature URL.
  devcontainerFeature: {
    name: 'ghcr.io/devcontainers/features/playbook-mock:99',
    opts: { version: '99.0.0', playbookFlag: true },
  },
  // Distinctive VSCode extension id so the assertion verifies the
  // synthetic pack's contribution specifically.
  devcontainerExtensions: ['playbook-vendor.playbook-mock'],
} as unknown as LanguageSupport;

// ─── Registry mutation ──────────────────────────────────────────────────────
// `vi.mock` re-exports don't reach module-internal `LANGUAGES` references
// (helper functions like `allSourceExtensions` close over the in-module
// binding, not the export). Mutating the array directly works because all
// consumers iterate `LANGUAGES.flatMap(...)` / `LANGUAGES.filter(...)` —
// fresh read each call. The `readonly` type marker is compile-time only.
//
// One-time consumers that capture state at module-load (e.g.
// `DEFAULT_VERSIONS` and `generic.ts`'s `SOURCE_EXTS` const) freeze before
// this beforeAll runs — those are tested separately via the LP.6
// `buildVariables` / `buildConditions` paths, which iterate fresh.
beforeAll(() => {
  (LANGUAGES as unknown as LanguageSupport[]).push(mockPlaybookPack);
});

afterAll(() => {
  const arr = LANGUAGES as unknown as LanguageSupport[];
  const idx = arr.indexOf(mockPlaybookPack);
  if (idx >= 0) arr.splice(idx, 1);
});

describe('recipe playbook — synthetic pack', () => {
  it('the mocked registry includes the mock pack', () => {
    expect(LANGUAGES.find((l) => (l.id as string) === 'playbook')).toBeDefined();
  });

  // ─── Iteration-based consumers (LP.3, LP.6, LP.7) ─────────────────────────

  it('allSourceExtensions includes the mock pack extensions (LP.3)', () => {
    const exts = allSourceExtensions();
    expect(exts).toContain('.pbk');
    expect(exts).toContain('.pbkx');
  });

  it('allTestFilePatterns includes the mock pack patterns (LP.3)', () => {
    const patterns = allTestFilePatterns();
    expect(patterns).toContain('*Test.pbk');
    expect(patterns).toContain('src/test/playbook/*.pbk');
  });

  // D028 (2.4.7): autogen pattern registry helper should iterate
  // every pack's declared patterns. Synthetic pack contributes
  // `*.designer.pbk` / `*.g.pbk` — both should appear.
  it('allAutogenSourcePatterns includes the mock pack patterns (D028)', () => {
    const patterns = allAutogenSourcePatterns();
    expect(patterns).toContain('*.designer.pbk');
    expect(patterns).toContain('*.g.pbk');
    // Also confirm csharp's declared patterns still flow through
    // (regression guard against the helper accidentally returning
    // only the most-recently-pushed pack's contributions).
    expect(patterns).toContain('*.designer.cs');
    expect(patterns).toContain('*.g.cs');
  });

  // D027 (2.4.7): doc-comment pattern registry helper iterates every
  // pack. Synthetic pack contributes `^playbook-doc:`; real packs'
  // canonical shapes should also flow through.
  it('allDocCommentPatterns includes the mock pack pattern (D027)', () => {
    const patterns = allDocCommentPatterns();
    expect(patterns).toContain('^playbook-doc:');
    // Real packs' canonical doc-comment markers (regression guard
    // against helper returning only the synthetic contribution).
    expect(patterns).toContain('^[[:space:]]*///'); // csharp / rust outer doc
    expect(patterns).toContain('/\\*\\*'); // typescript JSDoc / kotlin KDoc / java Javadoc
  });

  // D034 (2.4.7): TLS-bypass pattern registry helper iterates every
  // pack. Synthetic pack contributes `PlaybookInsecureTransport`;
  // real packs' canonical idioms should also appear.
  it('allTlsBypassPatterns includes the mock pack pattern (D034)', () => {
    const patterns = allTlsBypassPatterns();
    expect(patterns).toContain('PlaybookInsecureTransport');
    // Real packs' canonical TLS-bypass tokens (regression guard).
    expect(patterns).toContain('ServerCertificateValidationCallback'); // csharp
    expect(patterns).toContain('InsecureSkipVerify[[:space:]]*:[[:space:]]*true'); // go
    expect(patterns).toContain('NODE_TLS_REJECT_UNAUTHORIZED.*0'); // typescript
  });

  // 2.16: dependency-manifest pattern registry helper iterates every pack
  // that declares the `depVulns` capability. Synthetic pack contributes
  // `playbook.lock` / `*.pbkproj`; real packs' manifests should also flow so
  // the incremental dep-audit skip stays empirically pack-driven (adding a
  // pack auto-extends the skip's manifest awareness).
  it('allDependencyManifestPatterns includes the mock pack patterns (2.16)', () => {
    const patterns = allDependencyManifestPatterns([...LANGUAGES]);
    expect(patterns).toContain('playbook.lock');
    expect(patterns).toContain('*.pbkproj');
    // Real packs' manifests also flow through (regression guard against the
    // helper returning only the synthetic contribution).
    expect(patterns).toContain('package.json'); // typescript
    expect(patterns).toContain('go.mod'); // go
    expect(patterns).toContain('*.csproj'); // csharp
  });

  // Nested dep-audit roots (the nested-lockfile gap): the per-root dispatch
  // reads the pack's DECLARED lockfilePatterns — a synthetic pack with a
  // nested `playbook.lock` gets its gatherOutcome invoked once per root.
  it("gatherPackDepVulnsAcrossRoots audits the synthetic pack's nested lockfile roots", async () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'dxkit-playbook-nested-'));
    try {
      fs.mkdirSync(path.join(dir, 'apps', 'svc'), { recursive: true });
      fs.writeFileSync(path.join(dir, 'playbook.lock'), '{}');
      fs.writeFileSync(path.join(dir, 'apps', 'svc', 'playbook.lock'), '{}');
      const calls: string[] = [];
      const pack = {
        ...mockPlaybookPack,
        capabilities: {
          ...mockPlaybookPack.capabilities,
          depVulns: {
            ...mockPlaybookPack.capabilities!.depVulns!,
            async gatherOutcome(d: string) {
              calls.push(path.relative(dir, d).split(path.sep).join('/') || '.');
              return { kind: 'no-manifest' as const, reason: 'mock' };
            },
          },
        },
      };
      clearWalkPathsCache();
      await gatherPackDepVulnsAcrossRoots(pack as never, dir, undefined);
      expect(calls.sort()).toEqual(['.', 'apps/svc']);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
      clearWalkPathsCache();
    }
  });

  it('changedFilesTouchDependencyManifest detects the mock pack manifest (2.16)', () => {
    const packs = [...LANGUAGES];
    // A changed synthetic manifest (nested in a monorepo) is detected.
    expect(changedFilesTouchDependencyManifest(['services/a/playbook.lock'], packs)).toBe(true);
    expect(changedFilesTouchDependencyManifest(['app/My.pbkproj'], packs)).toBe(true);
    // A pure source-only change is NOT flagged → the dep audit may be skipped.
    expect(changedFilesTouchDependencyManifest(['src/main.pbk', 'README.md'], packs)).toBe(false);
  });

  // 2.23: the correctness floor iterates `activeCorrectnessProviders`, so a
  // synthetic pack that declares a `correctness` provider must be picked up by
  // the registry helper AND surface its checks through `runCorrectnessFloor` —
  // codifying "the liveness floor is pack-driven, not analyzer-by-analyzer."
  // Catches "the runner stopped iterating the registry" empirically.
  it('activeCorrectnessProviders + runCorrectnessFloor pick up the mock pack (2.23)', () => {
    const packs = [...LANGUAGES];
    const providers = activeCorrectnessProviders(packs);
    expect(providers.some((p) => (p.id as string) === 'playbook')).toBe(true);
    // The runner emits the synthetic pack's checks. Exec is injected, so no
    // real toolchain runs — this proves dispatch, not execution.
    const result = runCorrectnessFloor({
      cwd: '/nonexistent-repo',
      changedFiles: ['a.pbk'],
      scope: 'affected',
      packs,
      exec: () => ({ available: true, code: 0, output: '' }),
    });
    const playbookChecks = result.checks
      .filter((c) => (c.pack as string) === 'playbook')
      .map((c) => c.label);
    expect(playbookChecks).toContain('playbook-typecheck');
    expect(playbookChecks).toContain('playbook-tests');
  });

  // custom-check flagship: the lint gate iterates `activeLintGateProviders`, so a
  // synthetic pack that declares a `lintGate` provider must surface a
  // `lint:<pack>` spec through `lintGateSpecs` — codifying "the lint gate is a
  // pack-driven consumer of the one custom-check runner seam."
  it('activeLintGateProviders + lintGateSpecs pick up the mock pack lint gate', () => {
    const packs = [...LANGUAGES];
    const providers = activeLintGateProviders(packs);
    expect(providers.some((p) => (p.id as string) === 'playbook')).toBe(true);
    const specs = lintGateSpecs(
      packs,
      { cwd: '/nonexistent-repo', changedFiles: [] },
      {
        enabled: true,
        blocking: true,
      },
    );
    const playbookSpec = specs.find((s) => s.name === 'lint:playbook');
    expect(playbookSpec).toBeDefined();
    expect(playbookSpec?.command.bin).toBe('playbook-lint-mock');
    expect(playbookSpec?.blocking).toBe(true);
    expect(playbookSpec?.parse).toEqual({ mode: 'regex', pattern: expect.any(String) });
    // Disabled lint policy yields nothing (opt-in default off).
    expect(lintGateSpecs(packs, { cwd: '/x', changedFiles: [] }, undefined)).toEqual([]);
  });

  // 2.7 Sprint 1: exported-symbol detection registry helper iterates
  // every pack that declares the capability. Synthetic pack contributes
  // a distinctive strategy string; real packs' declarations should also
  // appear so the helper's union is empirically pack-driven (the
  // architecture-stopped-being-pack-driven regression guard).
  it('allExportDetectionDeclarations includes the mock pack contribution (2.7)', () => {
    const declarations = allExportDetectionDeclarations();
    const playbookEntry = declarations.find((d) => (d.pack as string) === 'playbook');
    expect(playbookEntry).toBeDefined();
    expect(playbookEntry?.reliability).toBe('partial');
    expect(playbookEntry?.strategy).toContain('playbook-mock-export-strategy');
    // Real packs' declarations also flow through (regression guard
    // against the helper returning only the synthetic contribution).
    const reliabilityByPack = new Map(declarations.map((d) => [d.pack, d.reliability]));
    expect(reliabilityByPack.get('typescript')).toBe('full');
    expect(reliabilityByPack.get('python')).toBe('partial');
    expect(reliabilityByPack.get('ruby')).toBe('unreliable');
  });

  it('buildDevcontainerFeatures picks up the synthetic pack contribution (Phase 2.5.1)', () => {
    // Activate only the synthetic pack via its flag so we observe its
    // contribution without bleeding real pack features into the
    // assertion.
    const flags = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const features = buildDevcontainerFeatures(flags);
    // Always-on entries land regardless of active packs.
    expect(features['ghcr.io/devcontainers/features/node:1']).toBeDefined();
    expect(features['ghcr.io/devcontainers/features/github-cli:1']).toBeDefined();
    // Synthetic-pack contribution flows through without any
    // code change to installDevcontainer or buildDevcontainerFeatures.
    expect(features['ghcr.io/devcontainers/features/playbook-mock:99']).toBeDefined();
    expect(features['ghcr.io/devcontainers/features/playbook-mock:99']).toEqual({
      version: '99.0.0',
      playbookFlag: true,
    });
  });

  it('buildDevcontainerExtensions picks up the synthetic pack contribution', () => {
    // Same activation pattern as the buildDevcontainerFeatures test: only
    // the synthetic pack is active, so we observe its extension landing
    // without bleeding real pack extensions into the assertion.
    const flags = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const extensions = buildDevcontainerExtensions(flags);
    // Always-on extensions land regardless of active packs.
    expect(extensions).toContain('anthropic.claude-code');
    expect(extensions).toContain('github.vscode-github-actions');
    expect(extensions).toContain('github.vscode-pull-request-github');
    // Synthetic-pack contribution flows through without any code change
    // to installDevcontainer or buildDevcontainerExtensions — same
    // pack-driven recipe as buildDevcontainerFeatures.
    expect(extensions).toContain('playbook-vendor.playbook-mock');
    // Order stability: always-on entries come before per-pack ones.
    expect(extensions.indexOf('anthropic.claude-code')).toBeLessThan(
      extensions.indexOf('playbook-vendor.playbook-mock'),
    );
  });

  // D030 (2.4.7): hygiene scope's extension list was hardcoded since
  // Phase 6. After D030 it derives from `allSourceExtensions()`. After
  // G_v4_7 (2.4.7 class-fix) the consumer of that registry is
  // `walkSourceFiles` (default opts) instead of a `--include` flag
  // string, but the invariant is identical: when a synthetic pack
  // joins the registry, its extensions MUST flow without code changes
  // in gather.ts. LP-A5 in `scripts/check-architecture.sh` catches
  // the static shape; this assertion catches semantic drift at runtime.
  it('allSourceExtensions includes the mock pack extensions (D030 / LP-A5 / G_v4_7)', () => {
    const exts = allSourceExtensions();
    expect(exts).toContain('.pbk');
    expect(exts).toContain('.pbkx');
  });

  // DEFAULT_VERSIONS is captured at module load, BEFORE this test's
  // beforeAll mutates LANGUAGES — so we can't assert against it here.
  // Coverage for LP.6's defaultVersion plumbing comes via buildVariables
  // below, which iterates LANGUAGES fresh on every call.

  it('buildVariables emits the mock pack <KEY>_VERSION (LP.6)', () => {
    const fakeConfig = makeFakeConfig({ playbook: true, playbookVersion: '99.0.0' });
    const v = buildVariables(fakeConfig);
    expect(v.PLAYBOOK_VERSION).toBe('99.0.0');
  });

  it('buildConditions emits IF_PLAYBOOK for the mock pack (LP.6)', () => {
    const fakeConfig = makeFakeConfig({ playbook: true });
    const conditions = buildConditions(fakeConfig);
    expect(conditions.IF_PLAYBOOK).toBe(true);
  });

  it('buildConditions emits IF_PLAYBOOK=false when mock pack is inactive (LP.6)', () => {
    const fakeConfig = makeFakeConfig({ playbook: false });
    const conditions = buildConditions(fakeConfig);
    expect(conditions.IF_PLAYBOOK).toBe(false);
  });

  // CI runtime setup (2.32): the workflow templater unions each active pack's
  // ciSetup via allCiSetupSteps. The synthetic pack's distinctive step must flow
  // through — codifying "CI runtime setup is pack-driven, not Node-only."
  it('allCiSetupSteps includes the mock pack ciSetup step (stack-aware CI is pack-driven)', () => {
    const flags = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    // Without cwd: no detection, so the declared default renders.
    const steps = allCiSetupSteps(flags);
    const synthetic = steps.find((s) => s.uses === 'playbook/setup-playbook@v9');
    expect(synthetic).toBeDefined();
    expect(synthetic?.with?.['playbook-version']).toBe('9.9.9');

    // WITH cwd: the pack's `detectVersion` (42.0.0) is substituted into the
    // `versionInput` key — codifying "toolchain-version derivation is
    // pack-driven, not a hardcoded default." A new pack that declares
    // detectVersion + versionInput inherits this automatically.
    const derived = allCiSetupSteps(flags, '/tmp/any-repo');
    const syntheticDerived = derived.find((s) => s.uses === 'playbook/setup-playbook@v9');
    expect(syntheticDerived?.with?.['playbook-version']).toBe('42.0.0');
  });

  // ─── activeLanguagesFromFlags (LP.7) ──────────────────────────────────────

  it('activeLanguagesFromFlags activates the mock pack by id (LP.7 / 10f.4)', () => {
    // Cast `playbook: true` — `LanguageId` union is closed in production
    // (typescript/python/go/rust/csharp/kotlin); the synthetic mock pack
    // deliberately uses an id outside the union. The cast lives here
    // because the test injects a hypothetical extra pack to verify the
    // architecture iterates the registry rather than enumerating
    // hardcoded ids.
    const flags = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const active = activeLanguagesFromFlags(flags);
    expect(active.find((l) => (l.id as string) === 'playbook')).toBe(mockPlaybookPack);
  });

  it('activeLanguagesFromStack picks up the mock pack the same way', () => {
    const stack = {
      languages: {
        typescript: false,
        python: false,
        go: false,
        rust: false,
        csharp: false,
        kotlin: false,
        playbook: true,
      },
      framework: undefined,
      // Type-only stub — the assertion only reads .languages.
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const active = activeLanguagesFromStack(stack);
    expect(active.find((l) => (l.id as string) === 'playbook')).toBe(mockPlaybookPack);
  });

  // ─── buildRequiredTools (LP.2 + LP.7) ─────────────────────────────────────

  it('buildRequiredTools includes the mock pack when its flag is set (LP.2 + LP.7)', () => {
    // Mock pack declares zero tools to keep TOOL_DEFS lookup safe.
    const required = buildRequiredTools({
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any);
    // No assertion that mock-pack tools are added (it has none); we
    // assert the call doesn't blow up — i.e. activeLanguagesFromFlags
    // tolerates the unknown pack and includes it in iteration.
    expect(Array.isArray(required)).toBe(true);
  });

  // ─── detect (LP.5) ────────────────────────────────────────────────────────

  it('detect() invokes the mock pack’s detect(cwd) function (LP.5)', () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'recipe-playbook-'));
    try {
      const mockDetect = mockPlaybookPack.detect as ReturnType<typeof vi.fn>;
      mockDetect.mockClear();
      detect(tmpDir);
      expect(mockDetect).toHaveBeenCalledWith(tmpDir);
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  // ─── G_v4_8 (2.4.7 Phase C1.6): canonical security aggregator
  //     picks up contributions regardless of pack identity ─────────────
  //
  // The synthetic pack contributes a depVuln finding + (hypothetically)
  // a TLS-bypass rule. The aggregator's behavior must NOT depend on
  // which pack produced the data — language-agnostic per CLAUDE.md
  // rule 6. These assertions are the recipe-codified regression guard:
  // future language packs that feed security data through the standard
  // capability descriptors automatically inherit drift prevention.
  it('buildSecurityAggregate picks up depVuln findings regardless of pack identity (G_v4_8)', async () => {
    const { buildSecurityAggregate } = await import('../src/analyzers/security/aggregator');
    const aggregate = buildSecurityAggregate({
      secrets: { findings: [], toolUsed: null },
      fileFindings: [],
      codePatterns: { findings: [], toolUsed: null },
      tlsBypass: [],
      tlsBypassPatternCount: 0,
      depVulns: {
        tool: 'playbookc-mock',
        available: true,
        unavailableReason: '',
        findings: [
          {
            id: 'PBK-2026-001',
            package: 'playbook-lib',
            installedVersion: '1.0.0',
            severity: 'high',
            tool: 'playbookc-mock',
            fingerprint: 'fp-playbook-001',
          },
          {
            id: 'PBK-2026-002',
            package: 'playbook-lib',
            installedVersion: '1.0.0',
            severity: 'critical',
            tool: 'playbookc-mock',
            fingerprint: 'fp-playbook-002',
          },
        ],
      },
    });
    expect(aggregate.dependencyAdvisoryUniqueCount).toBe(2);
    expect(aggregate.depBySeverity.critical).toBe(1);
    expect(aggregate.depBySeverity.high).toBe(1);
    expect(aggregate.findingsByCategory.dependency).toHaveLength(2);
    // Rule 9: synthetic-pack dep-vuln findings carry the fingerprint
    // they entered with — the aggregator must not strip the canonical
    // identity. Future packs producing dep-vulns inherit this contract.
    for (const f of aggregate.findingsByCategory.dependency) {
      expect(f.fingerprint).toBeTruthy();
    }
  });

  it('buildSecurityAggregate collapses cross-tool TLS-bypass regardless of pack identity (G_v4_8 / D091)', async () => {
    const { buildSecurityAggregate } = await import('../src/analyzers/security/aggregator');
    // Synthetic pack contributes a `.pbk` file with a TLS-bypass
    // construct. The aggregator must collapse the two raw findings
    // (semgrep at line 72, registry at line 74) into ONE
    // CodeFinding via canonical-rule + line-window dedup — same
    // collapse rule that fires for TypeScript / C# / etc. Mirrors
    // D091's exact line numbers from the platform repo (ldap-spec.ts).
    const aggregate = buildSecurityAggregate({
      secrets: { findings: [], toolUsed: null },
      fileFindings: [],
      codePatterns: {
        toolUsed: 'semgrep',
        findings: [
          {
            severity: 'medium',
            category: 'code',
            cwe: 'CWE-295',
            rule: 'bypass-tls-verification',
            tool: 'semgrep',
            file: 'src/playbook/transport.pbk',
            line: 72,
            title: 'TLS bypass via semgrep',
          },
        ],
      },
      tlsBypass: [
        {
          severity: 'high',
          category: 'code',
          cwe: 'CWE-295',
          rule: 'tls-validation-disabled',
          tool: 'tls-bypass-registry',
          file: 'src/playbook/transport.pbk',
          line: 74,
          title: 'TLS bypass via registry grep',
        },
      ],
      tlsBypassPatternCount: 1, // synthetic pack declares one TLS-bypass pattern
      depVulns: { findings: [], tool: null, available: true, unavailableReason: '' },
    });
    expect(aggregate.findingsByCategory.code).toHaveLength(1);
    expect(aggregate.findingsByCategory.code[0].severity).toBe('high'); // max
    expect(aggregate.findingsByCategory.code[0].producedBy).toEqual([
      'semgrep',
      'tls-bypass-registry',
    ]);
    expect(aggregate.codeBySeverity.high).toBe(1);
    expect(aggregate.dedupCollisions).toHaveLength(1);
    // Rule 9: the collapsed CodeFinding carries a fingerprint stamped
    // by the canonical helper. Synthetic pack contributions inherit
    // the same identity contract that real packs do.
    expect(aggregate.findingsByCategory.code[0].fingerprint).toMatch(/^[0-9a-f]{16}$/);
  });

  // ─── ArchitecturalShape (2.4.7 C8): per-stack paths + vocabulary
  //     contributions flow through every cross-cutting consumer ─────────
  //
  // Pre-extension, src/analyzers/ carried hardcoded backend-centric
  // path patterns (`/controllers/`, `/services/`, `/models/`) and a
  // closed `SourceFile.type` enum. Adding a new pack with custom
  // conventions (a hypothetical sixth pack here, but the assertion
  // shape applies equally to a new real pack — Swift, PHP, etc.) had
  // no way to surface its primary architecture, route handlers, or
  // data models. Post-extension every consumer reads from the active-
  // pack union, so the synthetic pack's contributions appear without
  // any consumer-side code change.

  it('allPrimaryComponentPaths includes the mock pack contributions (C8)', () => {
    const flags = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const paths = allPrimaryComponentPaths(flags);
    expect(paths).toContain('/playbookplane/');
    expect(paths).toContain('/playbookbinder/');
    expect(paths).toContain('/playbookforms/');
  });

  it('allRoutePaths includes the mock pack route patterns (C8)', () => {
    const flags = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const paths = allRoutePaths(flags);
    expect(paths).toContain('/playbookroutes/');
  });

  it('allModelPaths includes the mock pack model patterns (C8)', () => {
    const flags = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const paths = allModelPaths(flags);
    expect(paths).toContain('/playbookmodels/');
  });

  // Flow: the httpFlow registry helper iterates every active pack. Synthetic
  // pack contributes distinctive `playbook*` descriptors; a real pack
  // (typescript) contributes its canonical fetch/decorator set — the union
  // must carry both, codifying "flow extraction is pack-driven."
  it('allHttpFlow includes the mock pack descriptor + the real typescript one', () => {
    const flags = {
      typescript: true,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const descriptors = allHttpFlow(flags);
    // Synthetic pack's descriptor flows through.
    const synthetic = descriptors.find((d) => d.clientCallees?.includes('playbookFetch'));
    expect(synthetic).toBeDefined();
    expect(synthetic?.routeDecorators).toContain('playbookGet');
    expect(synthetic?.methodAliases?.playbookdel).toBe('DELETE');
    // Real typescript pack's descriptor also flows through (regression guard
    // against the helper returning only the synthetic contribution).
    const real = descriptors.find((d) => d.clientCallees?.includes('fetch'));
    expect(real).toBeDefined();
    expect(real?.routeDecorators).toContain('del'); // LoopBack delete decorator
    expect(real?.routeRouterCallees?.bases).toContain('router'); // Express
    // File-convention routing flows through the same union (2.28): the
    // synthetic pack's fileRoutes descriptor is present, and the real
    // typescript pack's Next.js App Router descriptor is too.
    expect(synthetic?.fileRoutes?.handlerFile).toBe('playbookroute');
    expect(real?.fileRoutes?.handlerFile).toBe('route');
    expect(real?.fileRoutes?.baseDirs).toContain('app');
  });

  // File-route path algebra: the SHARED deriver consumes any pack's descriptor,
  // proving the route-group / dynamic-segment rules aren't hardcoded to Next.js.
  // The synthetic pack's own `playbookapp` base + `playbookroute` handler derive
  // a route through the identical code path the real TS pack uses.
  it('deriveFileRoutePath derives routes from the synthetic pack descriptor', () => {
    const flags = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const synthetic = allHttpFlow(flags).find((d) => d.fileRoutes?.handlerFile === 'playbookroute');
    expect(synthetic?.fileRoutes).toBeDefined();
    const fr = synthetic!.fileRoutes!;
    // Literal + dynamic + route-group all handled by the shared algebra, driven
    // purely off the synthetic pack's declared base/handler names.
    expect(deriveFileRoutePath('playbookapp/widgets/playbookroute.pbk', fr)).toBe('/widgets');
    expect(deriveFileRoutePath('playbookapp/widgets/[id]/playbookroute.pbk', fr)).toBe(
      '/widgets/{var}',
    );
    expect(deriveFileRoutePath('playbookapp/(group)/things/playbookroute.pbk', fr)).toBe('/things');
    // A non-handler file under the base derives nothing.
    expect(deriveFileRoutePath('playbookapp/widgets/other.pbk', fr)).toBeNull();
  });

  // END-TO-END extraction: the synthetic descriptor drives the ONE extractor
  // over a real grammar's shape. This is the proof that flow extraction is
  // descriptor-driven all the way down — not just that the registry unions
  // descriptors (the allHttpFlow test above), but that a pack's declared
  // tokens actually mint calls and routes with ZERO extractor edits. A new
  // language pack inherits exactly this path: declare grammars + httpFlow.
  it('the synthetic descriptor extracts calls + routes through the one extractor', async () => {
    const synthetic = mockPlaybookPack.httpFlow!;
    const shape = grammarShape('javascript')!; // any shaped grammar exercises the path
    const tree = await parseSource(
      `
      playbookFetch('/from-bare-callee');
      playbookClient.playbookGet('/from-member-call');
      playbookApp.playbookGet('/from-router-call', handler);
      `,
      'javascript',
    );
    const flow = extractFromTree(tree!.rootNode, synthetic, shape, 'widget.pbk');
    // Every construct family recognized off the DESCRIPTOR's tokens, with the
    // alias map minting the verbs (playbookGet -> GET).
    expect(flow.calls.map((c) => `${c.method} ${c.path} via ${c.receiver}`).sort()).toEqual([
      'GET /from-bare-callee via playbookFetch',
      'GET /from-member-call via playbookClient',
    ]);
    expect(flow.routes.map((r) => `${r.method} ${r.path} via ${r.via}`)).toEqual([
      'GET /from-router-call via router-call',
    ]);
  });

  // Flow-gate trigger: the surface helpers iterate active packs (httpFlow +
  // grammar). The synthetic pack contributes `.pbk`; the real typescript pack
  // contributes `.ts`/`.tsx` — the union must carry both, and a changed file in
  // either extension must trip the trigger. Codifies "the ref-based flow-gate
  // skip is pack-driven, not a hardcoded extension list."
  it('allFlowSourceExtensions + changedFilesTouchFlowSurface pick up the mock pack', () => {
    const packs = [...LANGUAGES]; // LANGUAGES includes the injected synthetic pack (beforeAll)
    const exts = allFlowSourceExtensions(packs);
    expect(exts).toContain('.pbk'); // synthetic pack's flow extension
    expect(exts).toContain('.ts'); // real typescript pack's
    // A changed synthetic-flow source file trips the trigger.
    expect(changedFilesTouchFlowSurface(['app/Widget.pbk'], packs)).toBe(true);
    // A non-flow change does not.
    expect(changedFilesTouchFlowSurface(['README.md'], packs)).toBe(false);
  });

  // Model-schema: the registry helper + trigger iterate every active pack,
  // and the synthetic descriptor drives the ONE model extractor over a real
  // grammar's shapes — the same declaration-driven-all-the-way-down proof the
  // flow tests establish. A new language pack inherits exactly this path:
  // declare grammars + modelSchema, zero extractor edits.
  it('allModelSchema + the model-surface trigger pick up the mock pack', () => {
    const flags = {
      typescript: true,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const descriptors = allModelSchema(flags);
    expect(
      descriptors.some((d) => d.modelBaseClasses?.includes('PlaybookRecord')),
      'synthetic modelSchema missing from allModelSchema',
    ).toBe(true);
    const packs = [...LANGUAGES];
    expect(allModelSchemaSourceExtensions(packs)).toContain('.pbk');
    expect(changedFilesTouchModelSurface(['src/Widget.pbk'], packs)).toBe(true);
    expect(changedFilesTouchModelSurface(['README.md'], packs)).toBe(false);
    // Spec-only trigger: a configured spec path trips it even with no
    // model-capable extension match.
    expect(changedFilesTouchModelSurface(['api/models.json'], packs, ['api/models.json'])).toBe(
      true,
    );
  });

  it('the synthetic modelSchema descriptor extracts models through the one extractor', async () => {
    const synthetic = mockPlaybookPack.modelSchema!;
    // Any shaped grammar exercises the path — the JS family here.
    const modelShape = modelShapeForGrammar('javascript')!;
    const callShape = grammarShape('javascript')!;
    const tree = await parseSource(
      `
      @PlaybookEntity()
      class Widget {
        name = playbookColumn({ playbookNullable: true });
        count;
      }
      class Plain { x = 1; }
      `,
      'javascript',
    );
    const set = extractModelsFromTree(tree!.rootNode, synthetic, modelShape, callShape, 'w.pbk');
    expect(set.models.map((m) => m.name)).toEqual(['Widget']);
    expect(set.models[0].via).toBe('decorator');
    // The field constructor supplied the type token (folded through the
    // pack's typeAliases) and the optionality keyword.
    expect(set.models[0].fields).toEqual([
      { name: 'name', type: 'playbook-string', required: false },
      { name: 'count', type: null, required: null },
    ]);
  });

  it('allTestGapPriorityPaths unions all three buckets across active packs (C8)', () => {
    // typescript + playbook active: each contributes its own buckets
    // and the helper unions them. Asserts each pack's contribution
    // flows independently — regression guard against the union
    // accidentally returning only one pack's data.
    const flags = {
      typescript: true,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const taxonomy = allTestGapPriorityPaths(flags);
    // Synthetic pack contributions
    expect(taxonomy.critical).toContain('/playbookauth/');
    expect(taxonomy.high).toContain('/playbookplane/');
    expect(taxonomy.medium).toContain('/playbookbinder/');
    expect(taxonomy.medium).toContain('/playbookforms/');
    // typescript pack contributions (regression guard)
    expect(taxonomy.high).toContain('/controllers/');
    expect(taxonomy.medium).toContain('/components/');
  });

  it('dominantVocabulary returns the first declaring active pack (C8)', () => {
    // typescript declares vocabulary; activate ONLY the synthetic
    // pack and the helper must return the synthetic pack's
    // vocabulary — not silently fall through to typescript.
    const flagsPlaybookOnly = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const vocab = dominantVocabulary(flagsPlaybookOnly);
    expect(vocab).toBeDefined();
    expect(vocab!.components).toBe('playbook-planes');
    expect(vocab!.models).toBe('playbook-models');
    expect(vocab!.routes).toBe('playbook-routes');
  });

  it('dominantVocabulary weights by cloc lines when supplied (C8 follow-up)', () => {
    // typescript + playbook both active. Without cloc data,
    // typescript wins by registry order. WITH cloc data showing
    // playbook has 10× the lines, playbook wins instead.
    // Reproduces the polyglot scenario where a stray .py in a C#
    // repo activates python via registry order and steals the
    // vocabulary slot — fixed by weighting on real source-line counts.
    const flagsBothActive = {
      typescript: true,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;

    // Without cloc data: registry order wins → typescript first.
    const unweighted = dominantVocabulary(flagsBothActive);
    expect(unweighted).toBeDefined();
    expect(unweighted!.components).toBe('controllers/components');

    // WITH cloc data showing playbook dominates by line count, the
    // synthetic pack wins. clocLanguageNames on the synthetic pack
    // is undefined (mock doesn't declare any), so by name-match it
    // contributes 0 lines. We declare playbook's cloc name to
    // exercise the weighting end-to-end.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (mockPlaybookPack as any).clocLanguageNames = ['Playbook'];
    const weighted = dominantVocabulary(flagsBothActive, [
      { name: 'TypeScript', lines: 100 },
      { name: 'Playbook', lines: 1000 },
    ]);
    expect(weighted).toBeDefined();
    expect(weighted!.components).toBe('playbook-planes');

    // Inverse: when typescript dominates, typescript wins.
    const weightedReverse = dominantVocabulary(flagsBothActive, [
      { name: 'TypeScript', lines: 5000 },
      { name: 'Playbook', lines: 50 },
    ]);
    expect(weightedReverse!.components).toBe('controllers/components');

    // Cleanup: remove the clocLanguageNames addition so the rest
    // of the synthetic pack stays as originally declared.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    delete (mockPlaybookPack as any).clocLanguageNames;
  });

  it('dominantVocabulary returns null when no active pack declares vocabulary (C8)', () => {
    const flagsEmpty = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: false,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    expect(dominantVocabulary(flagsEmpty)).toBeNull();
  });

  it('gatherSourceFiles classifies files against the mock pack patterns (C8 / consumer)', async () => {
    // End-to-end assertion: the synthetic pack contributes a
    // primaryComponentPath (`/playbookplane/`), and the gather
    // consumer in src/analyzers/tests/gather.ts must classify a file
    // under that directory using the path's last segment as the
    // role label ("playbookplane"). Pre-extension this would have
    // fallen through to the hardcoded backend-centric enum and
    // returned 'other'.
    const { gatherSourceFiles } = await import('../src/analyzers/tests/gather');
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'recipe-playbook-archshape-'));
    try {
      const planeDir = path.join(tmpDir, 'src', 'playbookplane');
      fs.mkdirSync(planeDir, { recursive: true });
      fs.writeFileSync(path.join(planeDir, 'home.pbk'), 'export const x = 1;\n'.repeat(10));
      const flags = {
        typescript: false,
        python: false,
        go: false,
        rust: false,
        csharp: false,
        kotlin: false,
        java: false,
        ruby: false,
        playbook: true,
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
      } as any;
      const files = gatherSourceFiles(tmpDir, flags);
      const planeFile = files.find((f) => f.path.includes('playbookplane'));
      expect(planeFile).toBeDefined();
      // patternToLabel strips `/playbookplane/` to `'playbookplane'`.
      expect(planeFile!.type).toBe('playbookplane');
      // `/playbookplane/` was declared in testGapPriority.high so a
      // small file under it lands in MEDIUM (preserving the
      // pre-extension "large → HIGH, small → MEDIUM" semantic on
      // high-priority paths).
      expect(planeFile!.risk).toBe('medium');
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it('detectActiveLanguages calls the mock pack’s detect() and respects its return value', () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'recipe-playbook-'));
    try {
      const mockDetect = mockPlaybookPack.detect as ReturnType<typeof vi.fn>;
      mockDetect.mockClear();
      mockDetect.mockReturnValue(true);
      const active = detectActiveLanguages(tmpDir);
      expect(mockDetect).toHaveBeenCalledWith(tmpDir);
      expect(active.find((l) => (l.id as string) === 'playbook')).toBe(mockPlaybookPack);
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });
});

// ─── Helper ──────────────────────────────────────────────────────────────────
// Synthesize a `ResolvedConfig` with all required fields, optionally
// activating the mock pack via `playbook: true`.
function makeFakeConfig(opts: { playbook: boolean; playbookVersion?: string }) {
  return {
    languages: {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      playbook: opts.playbook,
    },
    versions: {
      python: '3.12',
      go: '1.24.0',
      node: '20',
      rust: 'stable',
      csharp: '8.0',
      kotlin: '1.9.22',
      playbook: opts.playbookVersion ?? '99.0.0',
    },
    coverageThreshold: '80',
    projectName: 'test',
    projectDescription: '',
    framework: undefined,
    infrastructure: { docker: false, postgres: false, redis: false },
    requiredTools: [],
    precommit: false,
    qualityChecks: false,
    aiSessions: false,
    aiPrompts: false,
    claudeCode: false,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } as any;
}
