/**
 * Phase 10i.0-LP.7 — recipe-playbook synthesis test.
 *
 * The durable guarantee that the LP architecture is *truly* pack-driven.
 *
 * Defines a synthetic pack (`mockPlaybookPack`) implementing every
 * `LanguageSupport` field, mocks the registry to include it, and asserts
 * each pack-iterating consumer picks up its contributions. If a future PR
 * re-introduces hardcoded language coupling — even subtly, even in a
 * consumer not yet known to the LP audit — this test fails.
 *
 * What's covered (LP.1 through LP.6 deliverables):
 *   - allSourceExtensions / allTestFilePatterns iterate the registry
 *   - DEFAULT_VERSIONS pulls each pack's defaultVersion
 *   - buildVariables emits <KEY>_VERSION for every pack
 *   - buildConditions emits IF_<KEY> for every pack
 *   - activeLanguagesFromFlags activates a pack when its versionKey flag
 *     is true in the stack (LP.7 made this pack-driven)
 *   - buildRequiredTools concatenates active packs' tools
 *   - detect() iterates LANGUAGES and calls each pack's .detect(cwd)
 *
 * Synthetic-id choice (`'playbook'`):
 *   The mock uses an id deliberately outside the `LanguageId` union so it
 *   never collides with a real pack. Phase 10j.1 (Kotlin) surfaced this:
 *   the original mock used `'kotlin'` as a placeholder, then collided
 *   when the real Kotlin pack landed. The lesson generalised — synthetic
 *   ids should be unmistakably non-language (`playbook`) so this test
 *   keeps working as future packs are added without further renames.
 *
 * Post-10f.4 note:
 *   `DetectedStack.languages` is now `Record<LanguageId, boolean>`. The
 *   synthetic pack's id is not in the union, so the test casts the
 *   stack/flags object via `as any` to inject the synthetic flag. Real
 *   packs don't need any cast.
 */

import { describe, it, expect, vi, beforeAll, afterAll } from 'vitest';
import type { LanguageSupport } from '../src/languages';
import {
  LANGUAGES,
  allAutogenSourcePatterns,
  allDependencyManifestPatterns,
  changedFilesTouchDependencyManifest,
  allDocCommentPatterns,
  allExportDetectionDeclarations,
  allModelPaths,
  allPrimaryComponentPaths,
  allRoutePaths,
  allSourceExtensions,
  allTestFilePatterns,
  allTestGapPriorityPaths,
  allTlsBypassPatterns,
  activeLanguagesFromFlags,
  activeLanguagesFromStack,
  buildDevcontainerExtensions,
  buildDevcontainerFeatures,
  detectActiveLanguages,
  dominantVocabulary,
} from '../src/languages';
import { buildVariables, buildConditions } from '../src/constants';
import { buildRequiredTools } from '../src/analyzers/tools/tool-registry';
import { detect } from '../src/detect';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

// ─── The mock synthetic pack ────────────────────────────────────────────────
// Distinctive extensions/patterns/binaries (`.pbk`, `playbookc-mock`) so the
// assertions verify the *synthetic* contributions specifically, never
// accidentally satisfied by a real pack that happens to share a token.
const mockPlaybookPack = {
  id: 'playbook',
  displayName: 'Playbook (synthetic — recipe playbook)',
  sourceExtensions: ['.pbk', '.pbkx'],
  testFilePatterns: ['*Test.pbk', 'src/test/playbook/*.pbk'],
  extraExcludes: ['playbook-build', '.playbook-cache'],
  autogeneratedSourcePatterns: ['*.designer.pbk', '*.g.pbk'],
  docCommentPatterns: ['^playbook-doc:'],
  tlsBypassPatterns: ['PlaybookInsecureTransport'],
  // Distinctive strategy string so the assertion verifies the synthetic
  // pack's contribution specifically, never accidentally satisfied by a
  // real pack that happens to share a token.
  exportDetection: {
    reliability: 'partial' as const,
    strategy: 'playbook-mock-export-strategy: detect via @playbook-export annotation',
  },
  // Architectural-shape contribution. Distinctive path tokens
  // (`/playbookplane/`, `/playbookbinder/`, `/playbookforms/`,
  // `/playbookmodels/`, `/playbookroutes/`) so assertions verify
  // the synthetic pack's paths specifically — never accidentally
  // satisfied by a real pack that shares a token.
  architecturalShape: {
    primaryComponentPaths: ['/playbookplane/', '/playbookbinder/', '/playbookforms/'],
    routePaths: ['/playbookroutes/'],
    modelPaths: ['/playbookmodels/'],
    vocabulary: {
      components: 'playbook-planes',
      models: 'playbook-models',
      routes: 'playbook-routes',
    },
    testGapPriority: {
      critical: ['/playbookauth/'],
      high: ['/playbookplane/'],
      medium: ['/playbookbinder/', '/playbookforms/'],
    },
  },
  detect: vi.fn(() => false),
  tools: [],
  semgrepRulesets: [],
  capabilities: {
    coverage: {
      source: 'playbook-mock',
      async gather() {
        return null;
      },
    },
    // Distinctive manifest patterns so the assertion verifies the synthetic
    // pack's dependency-manifest contribution flows through the registry
    // helpers that drive the incremental dep-audit skip (2.16).
    depVulns: {
      source: 'playbook-mock',
      manifestPatterns: ['playbook.lock', '*.pbkproj'],
      async gather() {
        return null;
      },
      async gatherOutcome() {
        return { kind: 'no-manifest', reason: 'mock' };
      },
    },
  },
  permissions: ['Bash(mock-playbook-permission:*)'],
  ruleFile: 'playbook-mock.md',
  cliBinaries: ['playbookc-mock'],
  defaultVersion: '99.0.0',
  versionKey: 'playbook',
  // Distinctive feature name so the assertion verifies the synthetic
  // pack's contribution specifically, never accidentally satisfied by
  // a real pack that shares a feature URL.
  devcontainerFeature: {
    name: 'ghcr.io/devcontainers/features/playbook-mock:99',
    opts: { version: '99.0.0', playbookFlag: true },
  },
  // Distinctive VSCode extension id so the assertion verifies the
  // synthetic pack's contribution specifically.
  devcontainerExtensions: ['playbook-vendor.playbook-mock'],
} as unknown as LanguageSupport;

// ─── Registry mutation ──────────────────────────────────────────────────────
// `vi.mock` re-exports don't reach module-internal `LANGUAGES` references
// (helper functions like `allSourceExtensions` close over the in-module
// binding, not the export). Mutating the array directly works because all
// consumers iterate `LANGUAGES.flatMap(...)` / `LANGUAGES.filter(...)` —
// fresh read each call. The `readonly` type marker is compile-time only.
//
// One-time consumers that capture state at module-load (e.g.
// `DEFAULT_VERSIONS` and `generic.ts`'s `SOURCE_EXTS` const) freeze before
// this beforeAll runs — those are tested separately via the LP.6
// `buildVariables` / `buildConditions` paths, which iterate fresh.
beforeAll(() => {
  (LANGUAGES as unknown as LanguageSupport[]).push(mockPlaybookPack);
});

afterAll(() => {
  const arr = LANGUAGES as unknown as LanguageSupport[];
  const idx = arr.indexOf(mockPlaybookPack);
  if (idx >= 0) arr.splice(idx, 1);
});

describe('recipe playbook — synthetic pack', () => {
  it('the mocked registry includes the mock pack', () => {
    expect(LANGUAGES.find((l) => (l.id as string) === 'playbook')).toBeDefined();
  });

  // ─── Iteration-based consumers (LP.3, LP.6, LP.7) ─────────────────────────

  it('allSourceExtensions includes the mock pack extensions (LP.3)', () => {
    const exts = allSourceExtensions();
    expect(exts).toContain('.pbk');
    expect(exts).toContain('.pbkx');
  });

  it('allTestFilePatterns includes the mock pack patterns (LP.3)', () => {
    const patterns = allTestFilePatterns();
    expect(patterns).toContain('*Test.pbk');
    expect(patterns).toContain('src/test/playbook/*.pbk');
  });

  // D028 (2.4.7): autogen pattern registry helper should iterate
  // every pack's declared patterns. Synthetic pack contributes
  // `*.designer.pbk` / `*.g.pbk` — both should appear.
  it('allAutogenSourcePatterns includes the mock pack patterns (D028)', () => {
    const patterns = allAutogenSourcePatterns();
    expect(patterns).toContain('*.designer.pbk');
    expect(patterns).toContain('*.g.pbk');
    // Also confirm csharp's declared patterns still flow through
    // (regression guard against the helper accidentally returning
    // only the most-recently-pushed pack's contributions).
    expect(patterns).toContain('*.designer.cs');
    expect(patterns).toContain('*.g.cs');
  });

  // D027 (2.4.7): doc-comment pattern registry helper iterates every
  // pack. Synthetic pack contributes `^playbook-doc:`; real packs'
  // canonical shapes should also flow through.
  it('allDocCommentPatterns includes the mock pack pattern (D027)', () => {
    const patterns = allDocCommentPatterns();
    expect(patterns).toContain('^playbook-doc:');
    // Real packs' canonical doc-comment markers (regression guard
    // against helper returning only the synthetic contribution).
    expect(patterns).toContain('^[[:space:]]*///'); // csharp / rust outer doc
    expect(patterns).toContain('/\\*\\*'); // typescript JSDoc / kotlin KDoc / java Javadoc
  });

  // D034 (2.4.7): TLS-bypass pattern registry helper iterates every
  // pack. Synthetic pack contributes `PlaybookInsecureTransport`;
  // real packs' canonical idioms should also appear.
  it('allTlsBypassPatterns includes the mock pack pattern (D034)', () => {
    const patterns = allTlsBypassPatterns();
    expect(patterns).toContain('PlaybookInsecureTransport');
    // Real packs' canonical TLS-bypass tokens (regression guard).
    expect(patterns).toContain('ServerCertificateValidationCallback'); // csharp
    expect(patterns).toContain('InsecureSkipVerify[[:space:]]*:[[:space:]]*true'); // go
    expect(patterns).toContain('NODE_TLS_REJECT_UNAUTHORIZED.*0'); // typescript
  });

  // 2.16: dependency-manifest pattern registry helper iterates every pack
  // that declares the `depVulns` capability. Synthetic pack contributes
  // `playbook.lock` / `*.pbkproj`; real packs' manifests should also flow so
  // the incremental dep-audit skip stays empirically pack-driven (adding a
  // pack auto-extends the skip's manifest awareness).
  it('allDependencyManifestPatterns includes the mock pack patterns (2.16)', () => {
    const patterns = allDependencyManifestPatterns([...LANGUAGES]);
    expect(patterns).toContain('playbook.lock');
    expect(patterns).toContain('*.pbkproj');
    // Real packs' manifests also flow through (regression guard against the
    // helper returning only the synthetic contribution).
    expect(patterns).toContain('package.json'); // typescript
    expect(patterns).toContain('go.mod'); // go
    expect(patterns).toContain('*.csproj'); // csharp
  });

  it('changedFilesTouchDependencyManifest detects the mock pack manifest (2.16)', () => {
    const packs = [...LANGUAGES];
    // A changed synthetic manifest (nested in a monorepo) is detected.
    expect(changedFilesTouchDependencyManifest(['services/a/playbook.lock'], packs)).toBe(true);
    expect(changedFilesTouchDependencyManifest(['app/My.pbkproj'], packs)).toBe(true);
    // A pure source-only change is NOT flagged → the dep audit may be skipped.
    expect(changedFilesTouchDependencyManifest(['src/main.pbk', 'README.md'], packs)).toBe(false);
  });

  // 2.7 Sprint 1: exported-symbol detection registry helper iterates
  // every pack that declares the capability. Synthetic pack contributes
  // a distinctive strategy string; real packs' declarations should also
  // appear so the helper's union is empirically pack-driven (the
  // architecture-stopped-being-pack-driven regression guard).
  it('allExportDetectionDeclarations includes the mock pack contribution (2.7)', () => {
    const declarations = allExportDetectionDeclarations();
    const playbookEntry = declarations.find((d) => (d.pack as string) === 'playbook');
    expect(playbookEntry).toBeDefined();
    expect(playbookEntry?.reliability).toBe('partial');
    expect(playbookEntry?.strategy).toContain('playbook-mock-export-strategy');
    // Real packs' declarations also flow through (regression guard
    // against the helper returning only the synthetic contribution).
    const reliabilityByPack = new Map(declarations.map((d) => [d.pack, d.reliability]));
    expect(reliabilityByPack.get('typescript')).toBe('full');
    expect(reliabilityByPack.get('python')).toBe('partial');
    expect(reliabilityByPack.get('ruby')).toBe('unreliable');
  });

  it('buildDevcontainerFeatures picks up the synthetic pack contribution (Phase 2.5.1)', () => {
    // Activate only the synthetic pack via its flag so we observe its
    // contribution without bleeding real pack features into the
    // assertion.
    const flags = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const features = buildDevcontainerFeatures(flags);
    // Always-on entries land regardless of active packs.
    expect(features['ghcr.io/devcontainers/features/node:1']).toBeDefined();
    expect(features['ghcr.io/devcontainers/features/github-cli:1']).toBeDefined();
    // Synthetic-pack contribution flows through without any
    // code change to installDevcontainer or buildDevcontainerFeatures.
    expect(features['ghcr.io/devcontainers/features/playbook-mock:99']).toBeDefined();
    expect(features['ghcr.io/devcontainers/features/playbook-mock:99']).toEqual({
      version: '99.0.0',
      playbookFlag: true,
    });
  });

  it('buildDevcontainerExtensions picks up the synthetic pack contribution', () => {
    // Same activation pattern as the buildDevcontainerFeatures test: only
    // the synthetic pack is active, so we observe its extension landing
    // without bleeding real pack extensions into the assertion.
    const flags = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const extensions = buildDevcontainerExtensions(flags);
    // Always-on extensions land regardless of active packs.
    expect(extensions).toContain('anthropic.claude-code');
    expect(extensions).toContain('github.vscode-github-actions');
    expect(extensions).toContain('github.vscode-pull-request-github');
    // Synthetic-pack contribution flows through without any code change
    // to installDevcontainer or buildDevcontainerExtensions — same
    // pack-driven recipe as buildDevcontainerFeatures.
    expect(extensions).toContain('playbook-vendor.playbook-mock');
    // Order stability: always-on entries come before per-pack ones.
    expect(extensions.indexOf('anthropic.claude-code')).toBeLessThan(
      extensions.indexOf('playbook-vendor.playbook-mock'),
    );
  });

  // D030 (2.4.7): hygiene scope's extension list was hardcoded since
  // Phase 6. After D030 it derives from `allSourceExtensions()`. After
  // G_v4_7 (2.4.7 class-fix) the consumer of that registry is
  // `walkSourceFiles` (default opts) instead of a `--include` flag
  // string, but the invariant is identical: when a synthetic pack
  // joins the registry, its extensions MUST flow without code changes
  // in gather.ts. LP-A5 in `scripts/check-architecture.sh` catches
  // the static shape; this assertion catches semantic drift at runtime.
  it('allSourceExtensions includes the mock pack extensions (D030 / LP-A5 / G_v4_7)', () => {
    const exts = allSourceExtensions();
    expect(exts).toContain('.pbk');
    expect(exts).toContain('.pbkx');
  });

  // DEFAULT_VERSIONS is captured at module load, BEFORE this test's
  // beforeAll mutates LANGUAGES — so we can't assert against it here.
  // Coverage for LP.6's defaultVersion plumbing comes via buildVariables
  // below, which iterates LANGUAGES fresh on every call.

  it('buildVariables emits the mock pack <KEY>_VERSION (LP.6)', () => {
    const fakeConfig = makeFakeConfig({ playbook: true, playbookVersion: '99.0.0' });
    const v = buildVariables(fakeConfig);
    expect(v.PLAYBOOK_VERSION).toBe('99.0.0');
  });

  it('buildConditions emits IF_PLAYBOOK for the mock pack (LP.6)', () => {
    const fakeConfig = makeFakeConfig({ playbook: true });
    const conditions = buildConditions(fakeConfig);
    expect(conditions.IF_PLAYBOOK).toBe(true);
  });

  it('buildConditions emits IF_PLAYBOOK=false when mock pack is inactive (LP.6)', () => {
    const fakeConfig = makeFakeConfig({ playbook: false });
    const conditions = buildConditions(fakeConfig);
    expect(conditions.IF_PLAYBOOK).toBe(false);
  });

  // ─── activeLanguagesFromFlags (LP.7) ──────────────────────────────────────

  it('activeLanguagesFromFlags activates the mock pack by id (LP.7 / 10f.4)', () => {
    // Cast `playbook: true` — `LanguageId` union is closed in production
    // (typescript/python/go/rust/csharp/kotlin); the synthetic mock pack
    // deliberately uses an id outside the union. The cast lives here
    // because the test injects a hypothetical extra pack to verify the
    // architecture iterates the registry rather than enumerating
    // hardcoded ids.
    const flags = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const active = activeLanguagesFromFlags(flags);
    expect(active.find((l) => (l.id as string) === 'playbook')).toBe(mockPlaybookPack);
  });

  it('activeLanguagesFromStack picks up the mock pack the same way', () => {
    const stack = {
      languages: {
        typescript: false,
        python: false,
        go: false,
        rust: false,
        csharp: false,
        kotlin: false,
        playbook: true,
      },
      framework: undefined,
      // Type-only stub — the assertion only reads .languages.
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const active = activeLanguagesFromStack(stack);
    expect(active.find((l) => (l.id as string) === 'playbook')).toBe(mockPlaybookPack);
  });

  // ─── buildRequiredTools (LP.2 + LP.7) ─────────────────────────────────────

  it('buildRequiredTools includes the mock pack when its flag is set (LP.2 + LP.7)', () => {
    // Mock pack declares zero tools to keep TOOL_DEFS lookup safe.
    const required = buildRequiredTools({
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any);
    // No assertion that mock-pack tools are added (it has none); we
    // assert the call doesn't blow up — i.e. activeLanguagesFromFlags
    // tolerates the unknown pack and includes it in iteration.
    expect(Array.isArray(required)).toBe(true);
  });

  // ─── detect (LP.5) ────────────────────────────────────────────────────────

  it('detect() invokes the mock pack’s detect(cwd) function (LP.5)', () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'recipe-playbook-'));
    try {
      const mockDetect = mockPlaybookPack.detect as ReturnType<typeof vi.fn>;
      mockDetect.mockClear();
      detect(tmpDir);
      expect(mockDetect).toHaveBeenCalledWith(tmpDir);
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  // ─── G_v4_8 (2.4.7 Phase C1.6): canonical security aggregator
  //     picks up contributions regardless of pack identity ─────────────
  //
  // The synthetic pack contributes a depVuln finding + (hypothetically)
  // a TLS-bypass rule. The aggregator's behavior must NOT depend on
  // which pack produced the data — language-agnostic per CLAUDE.md
  // rule 6. These assertions are the recipe-codified regression guard:
  // future language packs that feed security data through the standard
  // capability descriptors automatically inherit drift prevention.
  it('buildSecurityAggregate picks up depVuln findings regardless of pack identity (G_v4_8)', async () => {
    const { buildSecurityAggregate } = await import('../src/analyzers/security/aggregator');
    const aggregate = buildSecurityAggregate({
      secrets: { findings: [], toolUsed: null },
      fileFindings: [],
      codePatterns: { findings: [], toolUsed: null },
      tlsBypass: [],
      tlsBypassPatternCount: 0,
      depVulns: {
        tool: 'playbookc-mock',
        available: true,
        unavailableReason: '',
        findings: [
          {
            id: 'PBK-2026-001',
            package: 'playbook-lib',
            installedVersion: '1.0.0',
            severity: 'high',
            tool: 'playbookc-mock',
            fingerprint: 'fp-playbook-001',
          },
          {
            id: 'PBK-2026-002',
            package: 'playbook-lib',
            installedVersion: '1.0.0',
            severity: 'critical',
            tool: 'playbookc-mock',
            fingerprint: 'fp-playbook-002',
          },
        ],
      },
    });
    expect(aggregate.dependencyAdvisoryUniqueCount).toBe(2);
    expect(aggregate.depBySeverity.critical).toBe(1);
    expect(aggregate.depBySeverity.high).toBe(1);
    expect(aggregate.findingsByCategory.dependency).toHaveLength(2);
    // Rule 9: synthetic-pack dep-vuln findings carry the fingerprint
    // they entered with — the aggregator must not strip the canonical
    // identity. Future packs producing dep-vulns inherit this contract.
    for (const f of aggregate.findingsByCategory.dependency) {
      expect(f.fingerprint).toBeTruthy();
    }
  });

  it('buildSecurityAggregate collapses cross-tool TLS-bypass regardless of pack identity (G_v4_8 / D091)', async () => {
    const { buildSecurityAggregate } = await import('../src/analyzers/security/aggregator');
    // Synthetic pack contributes a `.pbk` file with a TLS-bypass
    // construct. The aggregator must collapse the two raw findings
    // (semgrep at line 72, registry at line 74) into ONE
    // CodeFinding via canonical-rule + line-window dedup — same
    // collapse rule that fires for TypeScript / C# / etc. Mirrors
    // D091's exact line numbers from the platform repo (ldap-spec.ts).
    const aggregate = buildSecurityAggregate({
      secrets: { findings: [], toolUsed: null },
      fileFindings: [],
      codePatterns: {
        toolUsed: 'semgrep',
        findings: [
          {
            severity: 'medium',
            category: 'code',
            cwe: 'CWE-295',
            rule: 'bypass-tls-verification',
            tool: 'semgrep',
            file: 'src/playbook/transport.pbk',
            line: 72,
            title: 'TLS bypass via semgrep',
          },
        ],
      },
      tlsBypass: [
        {
          severity: 'high',
          category: 'code',
          cwe: 'CWE-295',
          rule: 'tls-validation-disabled',
          tool: 'tls-bypass-registry',
          file: 'src/playbook/transport.pbk',
          line: 74,
          title: 'TLS bypass via registry grep',
        },
      ],
      tlsBypassPatternCount: 1, // synthetic pack declares one TLS-bypass pattern
      depVulns: { findings: [], tool: null, available: true, unavailableReason: '' },
    });
    expect(aggregate.findingsByCategory.code).toHaveLength(1);
    expect(aggregate.findingsByCategory.code[0].severity).toBe('high'); // max
    expect(aggregate.findingsByCategory.code[0].producedBy).toEqual([
      'semgrep',
      'tls-bypass-registry',
    ]);
    expect(aggregate.codeBySeverity.high).toBe(1);
    expect(aggregate.dedupCollisions).toHaveLength(1);
    // Rule 9: the collapsed CodeFinding carries a fingerprint stamped
    // by the canonical helper. Synthetic pack contributions inherit
    // the same identity contract that real packs do.
    expect(aggregate.findingsByCategory.code[0].fingerprint).toMatch(/^[0-9a-f]{16}$/);
  });

  // ─── ArchitecturalShape (2.4.7 C8): per-stack paths + vocabulary
  //     contributions flow through every cross-cutting consumer ─────────
  //
  // Pre-extension, src/analyzers/ carried hardcoded backend-centric
  // path patterns (`/controllers/`, `/services/`, `/models/`) and a
  // closed `SourceFile.type` enum. Adding a new pack with custom
  // conventions (a hypothetical sixth pack here, but the assertion
  // shape applies equally to a new real pack — Swift, PHP, etc.) had
  // no way to surface its primary architecture, route handlers, or
  // data models. Post-extension every consumer reads from the active-
  // pack union, so the synthetic pack's contributions appear without
  // any consumer-side code change.

  it('allPrimaryComponentPaths includes the mock pack contributions (C8)', () => {
    const flags = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const paths = allPrimaryComponentPaths(flags);
    expect(paths).toContain('/playbookplane/');
    expect(paths).toContain('/playbookbinder/');
    expect(paths).toContain('/playbookforms/');
  });

  it('allRoutePaths includes the mock pack route patterns (C8)', () => {
    const flags = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const paths = allRoutePaths(flags);
    expect(paths).toContain('/playbookroutes/');
  });

  it('allModelPaths includes the mock pack model patterns (C8)', () => {
    const flags = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const paths = allModelPaths(flags);
    expect(paths).toContain('/playbookmodels/');
  });

  it('allTestGapPriorityPaths unions all three buckets across active packs (C8)', () => {
    // typescript + playbook active: each contributes its own buckets
    // and the helper unions them. Asserts each pack's contribution
    // flows independently — regression guard against the union
    // accidentally returning only one pack's data.
    const flags = {
      typescript: true,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const taxonomy = allTestGapPriorityPaths(flags);
    // Synthetic pack contributions
    expect(taxonomy.critical).toContain('/playbookauth/');
    expect(taxonomy.high).toContain('/playbookplane/');
    expect(taxonomy.medium).toContain('/playbookbinder/');
    expect(taxonomy.medium).toContain('/playbookforms/');
    // typescript pack contributions (regression guard)
    expect(taxonomy.high).toContain('/controllers/');
    expect(taxonomy.medium).toContain('/components/');
  });

  it('dominantVocabulary returns the first declaring active pack (C8)', () => {
    // typescript declares vocabulary; activate ONLY the synthetic
    // pack and the helper must return the synthetic pack's
    // vocabulary — not silently fall through to typescript.
    const flagsPlaybookOnly = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    const vocab = dominantVocabulary(flagsPlaybookOnly);
    expect(vocab).toBeDefined();
    expect(vocab!.components).toBe('playbook-planes');
    expect(vocab!.models).toBe('playbook-models');
    expect(vocab!.routes).toBe('playbook-routes');
  });

  it('dominantVocabulary weights by cloc lines when supplied (C8 follow-up)', () => {
    // typescript + playbook both active. Without cloc data,
    // typescript wins by registry order. WITH cloc data showing
    // playbook has 10× the lines, playbook wins instead.
    // Reproduces the polyglot scenario where a stray .py in a C#
    // repo activates python via registry order and steals the
    // vocabulary slot — fixed by weighting on real source-line counts.
    const flagsBothActive = {
      typescript: true,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: true,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;

    // Without cloc data: registry order wins → typescript first.
    const unweighted = dominantVocabulary(flagsBothActive);
    expect(unweighted).toBeDefined();
    expect(unweighted!.components).toBe('controllers/components');

    // WITH cloc data showing playbook dominates by line count, the
    // synthetic pack wins. clocLanguageNames on the synthetic pack
    // is undefined (mock doesn't declare any), so by name-match it
    // contributes 0 lines. We declare playbook's cloc name to
    // exercise the weighting end-to-end.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (mockPlaybookPack as any).clocLanguageNames = ['Playbook'];
    const weighted = dominantVocabulary(flagsBothActive, [
      { name: 'TypeScript', lines: 100 },
      { name: 'Playbook', lines: 1000 },
    ]);
    expect(weighted).toBeDefined();
    expect(weighted!.components).toBe('playbook-planes');

    // Inverse: when typescript dominates, typescript wins.
    const weightedReverse = dominantVocabulary(flagsBothActive, [
      { name: 'TypeScript', lines: 5000 },
      { name: 'Playbook', lines: 50 },
    ]);
    expect(weightedReverse!.components).toBe('controllers/components');

    // Cleanup: remove the clocLanguageNames addition so the rest
    // of the synthetic pack stays as originally declared.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    delete (mockPlaybookPack as any).clocLanguageNames;
  });

  it('dominantVocabulary returns null when no active pack declares vocabulary (C8)', () => {
    const flagsEmpty = {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      java: false,
      ruby: false,
      playbook: false,
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } as any;
    expect(dominantVocabulary(flagsEmpty)).toBeNull();
  });

  it('gatherSourceFiles classifies files against the mock pack patterns (C8 / consumer)', async () => {
    // End-to-end assertion: the synthetic pack contributes a
    // primaryComponentPath (`/playbookplane/`), and the gather
    // consumer in src/analyzers/tests/gather.ts must classify a file
    // under that directory using the path's last segment as the
    // role label ("playbookplane"). Pre-extension this would have
    // fallen through to the hardcoded backend-centric enum and
    // returned 'other'.
    const { gatherSourceFiles } = await import('../src/analyzers/tests/gather');
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'recipe-playbook-archshape-'));
    try {
      const planeDir = path.join(tmpDir, 'src', 'playbookplane');
      fs.mkdirSync(planeDir, { recursive: true });
      fs.writeFileSync(path.join(planeDir, 'home.pbk'), 'export const x = 1;\n'.repeat(10));
      const flags = {
        typescript: false,
        python: false,
        go: false,
        rust: false,
        csharp: false,
        kotlin: false,
        java: false,
        ruby: false,
        playbook: true,
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
      } as any;
      const files = gatherSourceFiles(tmpDir, flags);
      const planeFile = files.find((f) => f.path.includes('playbookplane'));
      expect(planeFile).toBeDefined();
      // patternToLabel strips `/playbookplane/` to `'playbookplane'`.
      expect(planeFile!.type).toBe('playbookplane');
      // `/playbookplane/` was declared in testGapPriority.high so a
      // small file under it lands in MEDIUM (preserving the
      // pre-extension "large → HIGH, small → MEDIUM" semantic on
      // high-priority paths).
      expect(planeFile!.risk).toBe('medium');
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });

  it('detectActiveLanguages calls the mock pack’s detect() and respects its return value', () => {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'recipe-playbook-'));
    try {
      const mockDetect = mockPlaybookPack.detect as ReturnType<typeof vi.fn>;
      mockDetect.mockClear();
      mockDetect.mockReturnValue(true);
      const active = detectActiveLanguages(tmpDir);
      expect(mockDetect).toHaveBeenCalledWith(tmpDir);
      expect(active.find((l) => (l.id as string) === 'playbook')).toBe(mockPlaybookPack);
    } finally {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    }
  });
});

// ─── Helper ──────────────────────────────────────────────────────────────────
// Synthesize a `ResolvedConfig` with all required fields, optionally
// activating the mock pack via `playbook: true`.
function makeFakeConfig(opts: { playbook: boolean; playbookVersion?: string }) {
  return {
    languages: {
      typescript: false,
      python: false,
      go: false,
      rust: false,
      csharp: false,
      kotlin: false,
      playbook: opts.playbook,
    },
    versions: {
      python: '3.12',
      go: '1.24.0',
      node: '20',
      rust: 'stable',
      csharp: '8.0',
      kotlin: '1.9.22',
      playbook: opts.playbookVersion ?? '99.0.0',
    },
    coverageThreshold: '80',
    projectName: 'test',
    projectDescription: '',
    framework: undefined,
    infrastructure: { docker: false, postgres: false, redis: false },
    requiredTools: [],
    precommit: false,
    qualityChecks: false,
    aiSessions: false,
    aiPrompts: false,
    claudeCode: false,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } as any;
}
