import type { DetectedStack } from '../types';
import type { LanguageId, LanguageSupport } from './types';
import { csharp } from './csharp';
import { go } from './go';
import { python } from './python';
import { rust } from './rust';
import { typescript } from './typescript';
import { kotlin } from './kotlin';
import { java } from './java';
import { ruby } from './ruby';

export type { LanguageId, LanguageSupport, LintSeverity, ProjectYamlContext } from './types';

export const LANGUAGES: readonly LanguageSupport[] = [
  python,
  typescript,
  csharp,
  go,
  rust,
  kotlin,
  java,
  ruby,
];

export function getLanguage(id: LanguageId): LanguageSupport | undefined {
  return LANGUAGES.find((l) => l.id === id);
}

export function detectActiveLanguages(cwd: string): LanguageSupport[] {
  return LANGUAGES.filter((l) => l.detect(cwd));
}

/**
 * Map a `DetectedStack` (or `ResolvedConfig`, which extends it) to the
 * set of `LanguageSupport` packs that are active for the project.
 * Pack-driven via `DetectedStack.languages` keyed on `LanguageId` —
 * adding a pack means extending `LanguageId` + registering in
 * `LANGUAGES`; this function never changes.
 */
export function activeLanguagesFromStack(stack: DetectedStack): LanguageSupport[] {
  return activeLanguagesFromFlags(stack.languages);
}

/**
 * Same as `activeLanguagesFromStack`, but for callers who only have
 * the `languages` sub-shape (e.g. `tool-registry.ts:buildRequiredTools`
 * receives `DetectedStack['languages']`, not the full stack).
 */
export function activeLanguagesFromFlags(flags: DetectedStack['languages']): LanguageSupport[] {
  return LANGUAGES.filter((l) => flags[l.id] ?? false);
}

/**
 * All source-file extensions across every registered pack, deduplicated.
 * The pack-driven analog of the pre-LP.3 hardcoded
 * `'.ts .tsx .js .jsx .py .go .rs .cs'` constant in `generic.ts` —
 * grows automatically as new packs land.
 */
export function allSourceExtensions(): string[] {
  return [...new Set(LANGUAGES.flatMap((l) => l.sourceExtensions))];
}

/**
 * All test-file patterns across every registered pack, deduplicated.
 * Patterns without a slash are basename-style (matched by find `-name`);
 * patterns containing a slash are path-anchored (e.g. Rust's
 * tests-directory glob for integration tests) and need find
 * `-path` semantics — see `splitTestFilePatterns()`.
 */
export function allTestFilePatterns(): string[] {
  return [...new Set(LANGUAGES.flatMap((l) => l.testFilePatterns))];
}

/**
 * All auto-generated source-file basename patterns across every
 * registered pack, deduplicated. D028 (2.4.7): consumers (currently
 * `src/analyzers/tools/generic.ts`) build find `-not -name` excludes
 * from this list to keep per-file metrics from being inflated by
 * generated code (designer.cs, *.pb.go, *Generated.java, etc.).
 *
 * Packs that don't declare `autogeneratedSourcePatterns` contribute
 * nothing — the helper returns the union of all declared patterns
 * across active+inactive packs. Conservative by design: a designer.cs
 * file in a polyglot repo with both csharp and go active is still
 * filtered even if the csharp pack happens to be inactive in this
 * cwd's scope.
 */
export function allAutogenSourcePatterns(): string[] {
  return [...new Set(LANGUAGES.flatMap((l) => l.autogeneratedSourcePatterns ?? []))];
}

/**
 * All doc-comment regex patterns across every registered pack,
 * deduplicated. D027 (2.4.7): consumed by `generic.ts` to build a
 * union grep alternation for `docCommentFiles`. Empty array when no
 * pack declares any patterns — caller short-circuits to 0.
 *
 * Scope mirrors `allAutogenSourcePatterns`: union across all packs
 * (active + inactive). A `///` line in a `.cs` file inside a
 * polyglot repo gets counted even if csharp isn't the dominant pack
 * — the false-positive rate across language boundaries is negligible
 * (e.g. `///` doesn't appear in `.py` files).
 */
export function allDocCommentPatterns(): string[] {
  return [...new Set(LANGUAGES.flatMap((l) => l.docCommentPatterns ?? []))];
}

/**
 * All TLS-bypass regex patterns across every registered pack,
 * deduplicated. D034 (2.4.7): consumed by `generic.ts` to build a
 * union grep alternation for `tlsDisabledCount` — a Security-score
 * input that previously matched only Node-shaped idioms.
 *
 * Scope mirrors `allDocCommentPatterns`: union across all packs
 * (active + inactive). A `.cs` file containing
 * `ServerCertificateValidationCallback = ...` in a polyglot repo
 * gets flagged regardless of which pack the customer "primarily" uses
 * — security findings should never be silently scoped out.
 */
export function allTlsBypassPatterns(): string[] {
  return [...new Set(LANGUAGES.flatMap((l) => l.tlsBypassPatterns ?? []))];
}

/**
 * Cloc language names declared by every pack, deduplicated. D073
 * (2.4.7): consumed by `gatherClocMetrics` to filter cloc's per-
 * language summary + `totalLines` aggregation down to "actual source
 * code" — JSON / XML / CSV / Markdown that cloc emits stay out of the
 * source-line counters that quality's Comment Ratio + health's
 * Documentation derive from. Pre-D073 cloc's `SUM` summed every
 * language including markup/data, deflating the dpl-studio comment
 * ratio (1.6M JSON lines dragged 25%-true C# comment ratio down to
 * 4.3%).
 *
 * Scope mirrors `allAutogenSourcePatterns` — union across active +
 * inactive packs. A `.cs` file in a polyglot repo gets counted even
 * when csharp isn't the detect-time dominant pack, which is fine:
 * cloc names map to languages, not pack-presence signals.
 */
export function allClocLanguageNames(): string[] {
  return [...new Set(LANGUAGES.flatMap((l) => l.clocLanguageNames ?? []))];
}

/**
 * Split test-file patterns into the two shapes find treats differently:
 * basename patterns (matched via `-name`) and path-anchored patterns
 * (matched via `-path`). Pre-LP.3, generic.ts used only `-name` and
 * silently missed Rust's integration tests under the tests directory
 * because that pattern doesn't match a basename.
 */
export function splitTestFilePatterns(patterns: string[] = allTestFilePatterns()): {
  nameOnly: string[];
  pathAnchored: string[];
} {
  return {
    nameOnly: patterns.filter((p) => !p.includes('/')),
    pathAnchored: patterns.filter((p) => p.includes('/')),
  };
}
