import type { LanguageId, ResolvedConfig } from '../types';
import type {
  CapabilityProvider,
  DepVulnsProvider,
  LicensesProvider,
} from './capabilities/provider';
import type {
  CoverageResult,
  ImportsResult,
  LintResult,
  TestFrameworkResult,
} from './capabilities/types';

// `LanguageId` lives in `src/types.ts` (where `DetectedStack.languages`
// references it) to avoid circular imports. Re-exported here for
// callers that import from the languages barrel.
export type { LanguageId } from '../types';

export type LintSeverity = 'critical' | 'high' | 'medium' | 'low';

/**
 * Capability providers a language pack may expose. Every data-producing
 * surface lives here after Phase 10e.C.5 — the legacy `gatherMetrics`
 * channel is gone, and the capability dispatcher is the only route from
 * a language pack to the analyzer layer. Each provider is optional so a
 * pack can ship incrementally as underlying tool support lands.
 */
export interface LanguagePackCapabilities {
  depVulns?: DepVulnsProvider;
  lint?: CapabilityProvider<LintResult>;
  coverage?: CapabilityProvider<CoverageResult>;
  testFramework?: CapabilityProvider<TestFrameworkResult>;
  imports?: CapabilityProvider<ImportsResult>;
  licenses?: LicensesProvider;
}

/**
 * Everything dxkit needs to know about a language lives in one implementation
 * of this interface. See `src/languages/index.ts` for the registry.
 *
 * Optional methods mean "feature not supported yet" — dispatchers should
 * tolerate their absence.
 */
export interface LanguageSupport {
  id: LanguageId;
  displayName: string;

  sourceExtensions: string[];
  testFilePatterns: string[];
  extraExcludes?: string[];

  /**
   * D028 (2.4.7): basename glob patterns identifying auto-generated
   * source files that should be EXCLUDED from per-file metrics
   * (source-file counts, files-over-500-lines, largest-file probes,
   * quality/maintainability scoring inputs). Common examples:
   *
   *   csharp: `['*.designer.cs', '*.g.cs', '*.g.i.cs', '*.generated.cs',
   *            '*.AssemblyInfo.cs', '*.AssemblyAttributes.cs']`
   *   go:     `['*.pb.go', '*_string.go']`        (protobuf, stringer)
   *   java:   `['*Generated.java']`               (Lombok, etc.)
   *
   * dpl-studio is the motivating case: Visual Studio's WinForms
   * designer generates `*.designer.cs` files that are typically large
   * (>500 lines), repetitive, and not authored — pre-D028 these
   * inflated Code Quality + Maintainability dimensions for any .NET
   * UI codebase. Each pack declares its own patterns so adding a new
   * pack (or extending an existing pack's patterns) auto-flows
   * through the cross-cutting `gatherGenericMetrics` filter.
   *
   * Optional — packs without canonical autogen conventions omit it.
   */
  autogeneratedSourcePatterns?: string[];

  /**
   * D027 (2.4.7): grep -E regex strings identifying lines that
   * contain a documentation comment in this language. The union of
   * every active pack's patterns drives `docCommentFiles` in
   * `gatherGenericMetrics` (the Documentation score input). Pre-D027
   * the regex was JS-shaped and the grep --include list was hardcoded
   * to TS / Python / Go extensions, so any csharp / kotlin / java /
   * rust / ruby project reported zero doc-comment files. dpl-studio
   * (3,234 .cs files with XML-doc triple-slash) is the motivating
   * case: Documentation score was pinned at 0/100.
   *
   * POSIX-compatible: prefer `[[:space:]]` over `\s`; escape regex
   * metacharacters for grep -E. Each entry is a standalone regex; the
   * registry unions them via a `\n`-separated pattern file (so embedded
   * single/double quotes in patterns don't break the shell).
   *
   * See each pack's `docCommentPatterns` declaration for the
   * canonical shape (csharp XML-doc, JSDoc/TSDoc, Python docstrings,
   * godoc, rustdoc, KDoc, Javadoc, YARD-style).
   *
   * Optional — packs without canonical doc-comment conventions omit it.
   */
  docCommentPatterns?: string[];

  /**
   * D034 (2.4.7): grep -E regex strings identifying TLS / certificate-
   * validation bypass idioms specific to this language's HTTP / network
   * stacks. The union of every pack's patterns drives `tlsDisabledCount`
   * in `gatherGenericMetrics` — surfaced through the Security score as
   * a `high`-severity code finding.
   *
   * Pre-D034 the regex only matched Node-shaped idioms
   * (`NODE_TLS_REJECT_UNAUTHORIZED`, `rejectUnauthorized: false`,
   * `VERIFY_SSL`) on `*.ts / *.js / *.py` includes. csharp's
   * `ServerCertificateValidationCallback`, go's `InsecureSkipVerify`,
   * rust's `danger_accept_invalid_certs`, java's `TrustAllX509TrustManager`,
   * ruby's `OpenSSL::SSL::VERIFY_NONE`, etc. were never detected. Each
   * pack now declares its own ecosystem-specific idioms.
   *
   * Same POSIX-grep rules as `docCommentPatterns`. Same union-via-
   * pattern-file mechanism in `generic.ts` (avoids shell escaping for
   * patterns containing `::`, quotes, etc.). False positives across
   * languages are negligible — `InsecureSkipVerify` doesn't appear in
   * `.py` files, etc.
   *
   * Optional — packs without canonical TLS-bypass idioms omit it.
   */
  tlsBypassPatterns?: string[];

  detect(cwd: string): boolean;

  tools: string[];
  semgrepRulesets: string[];

  /**
   * Tier a lint rule code into a severity bucket. Accepts `string | null |
   * undefined` because real lint output occasionally emits `ruleId: null`
   * (eslint with rule-disabled diagnostics) or omits the field entirely
   * (golangci-lint's "unknown linter" path). Implementations short-circuit
   * to `'low'` for non-string input — both `mapEslintRuleSeverity` and the
   * golangci-lint mapping rely on this contract for defensive parsing.
   */
  mapLintSeverity?(code: string | null | undefined): LintSeverity;

  /** Capability providers for the dispatcher channel. */
  capabilities?: LanguagePackCapabilities;

  /**
   * Bash-permission entries added to `.claude/settings.json` when this
   * pack is active in the project. `vyuh-dxkit init`/`update` iterates
   * `activeLanguagesFromStack(config)` and concatenates each pack's
   * permissions onto the base permission list.
   */
  permissions?: string[];

  /**
   * Filename under `src-templates/.claude/rules/` to copy to
   * `.claude/rules/<file>` when this pack is active. Frameworks like
   * `nextjs.md`, `loopback.md`, `express.md` are NOT pack-owned — they
   * stay hardcoded in `generator.ts` because they're framework-scoped,
   * not language-scoped.
   */
  ruleFile?: string;

  /**
   * Per-pack template→output pairs scaffolded by `vyuh-dxkit init` when
   * this pack is active. Templates live under
   * `src-templates/configs/<lang>/`. Skipped silently if the output
   * already exists (so `update` doesn't clobber user-customized
   * configs).
   */
  templateFiles?: { template: string; output: string }[];

  /**
   * External CLI binaries `vyuh-dxkit doctor` checks for when this pack
   * is active. Today this is the per-language toolchain (e.g. python +
   * ruff for python; dotnet for csharp). Surfacing missing binaries to
   * users is the doctor command's primary job.
   */
  cliBinaries?: string[];

  /**
   * Renders this pack's section under `languages:` in `.project.yaml`.
   * Receives the resolved project config + an `enabled` flag the
   * registry computes (since the YAML emits `enabled: false` for
   * inactive packs too — the section is iterated over ALL packs, not
   * just active ones). Returning a multi-line string (lines joined by
   * "\n") is conventional.
   */
  projectYamlBlock?: (ctx: ProjectYamlContext) => string;

  /**
   * Default language version surfaced in `DEFAULT_VERSIONS` (e.g. '3.12'
   * for Python, '20' for Node). Plumbed into template variables as
   * `<KEY>_VERSION` (uppercased `versionKey`) and into `.project.yaml`'s
   * `version:` field for inactive packs.
   */
  defaultVersion?: string;

  /**
   * Key under `DetectedStack.versions` where this pack's version lives —
   * AND the lowercase prefix used to derive template-variable + condition
   * names (`NODE_VERSION`, `IF_NODE`). Defaults to `id` when omitted.
   *
   * Necessary because the typescript pack uses `versionKey: 'node'` —
   * legacy template / condition naming predates the pack abstraction.
   * Removing this indirection requires renaming the templates'
   * `NODE_VERSION` / `IF_NODE` references to `TYPESCRIPT_VERSION` /
   * `IF_TYPESCRIPT`, which is a breaking template change tracked
   * alongside D009/D010 in 10f.4.
   */
  versionKey?: keyof import('../types').DetectedStack['versions'];
}

/** Context passed to `LanguageSupport.projectYamlBlock`. */
export interface ProjectYamlContext {
  config: ResolvedConfig;
  enabled: boolean;
}
