/**
 * Detailed test-gaps report — JSON schema + markdown formatter.
 */
import { TestGapsReport, SourceFile, RiskTier } from './types';
import { RankedAction, rank } from '../remediation';
import { buildTestGapsActions, countsFromReport } from './actions';
import { TestGapsCounts, scoreTestGapsCounts } from './scoring';

export interface TestGapsDetailedReport extends TestGapsReport {
  schemaVersion: string;
  coverageScore: number;
  actions: Array<RankedAction<TestGapsCounts>>;
}

export function buildTestGapsDetailed(report: TestGapsReport): TestGapsDetailedReport {
  const counts = countsFromReport(report);
  const actions = rank(buildTestGapsActions(report), counts, scoreTestGapsCounts);
  return {
    ...report,
    schemaVersion: '11',
    coverageScore: scoreTestGapsCounts(counts).score,
    actions,
  };
}

const TIER_ORDER: Record<RiskTier, number> = { critical: 0, high: 1, medium: 2, low: 3 };

export function formatTestGapsDetailedMarkdown(
  detailed: TestGapsDetailedReport,
  elapsed: string,
): string {
  const L: string[] = [];
  const s = detailed.summary;

  L.push('# Test Gap Analysis — Detailed');
  L.push('');
  L.push(`**Date:** ${detailed.analyzedAt.slice(0, 10)}`);
  L.push(`**Repository:** ${detailed.repo}`);
  L.push(`**Branch:** ${detailed.branch} (${detailed.commitSha})`);
  L.push(`**Effective Coverage:** ${s.effectiveCoverage}%`);
  L.push(`**Risk-Weighted Score:** ${detailed.coverageScore}/100`);
  L.push(`**Schema version:** ${detailed.schemaVersion}`);
  L.push('');
  L.push('---');
  L.push('');

  // Summary
  L.push('## Summary');
  L.push('');
  L.push('| Metric | Value |');
  L.push('|--------|------:|');
  L.push(
    `| Test files | ${s.testFiles} (active: ${s.activeTestFiles}, commented-out: ${s.commentedOutFiles}) |`,
  );
  L.push(`| Source files | ${s.sourceFiles} |`);
  L.push(`| Untested (CRITICAL) | ${s.untestedCritical} |`);
  L.push(`| Untested (HIGH) | ${s.untestedHigh} |`);
  L.push(`| Untested (MEDIUM) | ${s.untestedMedium} |`);
  L.push(`| Untested (LOW) | ${s.untestedLow} |`);
  L.push('');
  L.push('---');
  L.push('');

  // Actions
  L.push('## Recommended Actions');
  L.push('');
  if (detailed.actions.length === 0) {
    L.push('No gaps to close.');
  } else {
    L.push('Actions are ranked by projected risk-weighted score improvement.');
    L.push('');
    L.push('| # | Action | Score Δ | Projected |');
    L.push('|---|--------|--------:|----------:|');
    detailed.actions.forEach((a, i) => {
      L.push(`| ${i + 1} | ${a.title} | +${a.scoreDelta} | ${a.projectedScore}/100 |`);
    });
    L.push('');
    for (const a of detailed.actions) {
      L.push(`### ${a.title} (+${a.scoreDelta})`);
      L.push('');
      L.push(`- **ID:** \`${a.id}\``);
      L.push(`- **Baseline:** ${a.baselineScore}/100`);
      L.push(`- **Projected:** ${a.projectedScore}/100`);
      if (a.rationale) L.push(`- **Why:** ${a.rationale}`);
      if (a.evidence.length) {
        L.push('- **Files:**');
        for (const e of a.evidence.slice(0, 20)) {
          L.push(`  - \`${e.file}\` — ${e.message || e.rule}`);
        }
        if (a.evidence.length > 20) L.push(`  - … and ${a.evidence.length - 20} more`);
      }
      L.push('');
    }
  }
  L.push('---');
  L.push('');

  // Gaps inventory by risk tier
  L.push('## All Gaps by Risk Tier');
  L.push('');
  const sorted: SourceFile[] = [...detailed.gaps].sort(
    (a, b) => TIER_ORDER[a.risk] - TIER_ORDER[b.risk] || b.lines - a.lines,
  );
  const grouped: Record<RiskTier, SourceFile[]> = {
    critical: [],
    high: [],
    medium: [],
    low: [],
  };
  for (const g of sorted) grouped[g.risk].push(g);

  for (const tier of ['critical', 'high', 'medium', 'low'] as RiskTier[]) {
    const items = grouped[tier];
    if (items.length === 0) continue;
    L.push(`### ${tier.toUpperCase()} (${items.length})`);
    L.push('');
    L.push('| File | Type | Lines |');
    L.push('|------|------|------:|');
    for (const g of items.slice(0, 50)) {
      L.push(`| \`${g.path}\` | ${g.type} | ${g.lines} |`);
    }
    if (items.length > 50) L.push(`| … and ${items.length - 50} more | | |`);
    L.push('');
  }
  L.push('---');
  L.push('');

  L.push(`**Tools used:** ${detailed.toolsUsed.join(', ')}`);
  if (detailed.toolsUnavailable.length > 0) {
    L.push(`**Tools unavailable:** ${detailed.toolsUnavailable.join(', ')}`);
  }
  L.push(`**Analysis time:** ${elapsed}s`);
  L.push('');
  L.push(
    '*Generated by [VyuhLabs DXKit](https://www.npmjs.com/package/@vyuhlabs/dxkit) — detailed mode*',
  );
  return L.join('\n');
}
