/**
 * Test gap gathering — find test files, source files, match them, classify risk.
 *
 * Tool responsibilities:
 *   find  → enumerate test files and source files
 *   grep  → check if test files have active assertions (not just comments)
 *   wc    → line counts for risk classification
 */
import * as fs from 'fs';
import * as path from 'path';
import { walkSourceFiles } from '../tools/walk-source-files';
import { TestFile, SourceFile, RiskTier } from './types';

// G_v4_7 (2.4.7): both gatherTestFiles and gatherSourceFiles route
// through walkSourceFiles. Pre-migration each had its own find
// composition with subtly different test-pattern matching, exclusion
// handling, and autogen filtering. ONE walker, ONE definition of
// "what counts as a source file" — closes D075 for the test-gaps
// gather path.

// Patterns for security-critical files (CRITICAL risk)
const CRITICAL_PATTERNS = [
  /auth/i,
  /jwt/i,
  /password/i,
  /rbac/i,
  /crypto/i,
  /encrypt/i,
  /sanitiz/i,
  /validat/i,
  /security/i,
  /session/i,
  /token/i,
  /oauth/i,
  /saml/i,
  /keycloak/i,
  /ldap/i,
  /permission/i,
];

// ─── Test file discovery ────────────────────────────────────────────────────

export function gatherTestFiles(cwd: string): TestFile[] {
  // Walker computes test-files as (includeTests:true SET) MINUS
  // (includeTests:false SET). Test-pattern derivation is pack-driven
  // via `allTestFilePatterns()`, so adding a new pack auto-extends.
  const allFiles = new Set(walkSourceFiles(cwd, { includeTests: true }));
  const nonTestFiles = new Set(walkSourceFiles(cwd));
  const testFiles: TestFile[] = [];
  for (const p of allFiles) {
    if (nonTestFiles.has(p)) continue;
    const fullPath = path.join(cwd, p);
    testFiles.push({
      path: p,
      status: classifyTestFile(fullPath),
      framework: detectTestFramework(fullPath),
    });
  }
  return testFiles;
}

function classifyTestFile(fullPath: string): TestFile['status'] {
  let content: string;
  try {
    content = fs.readFileSync(fullPath, 'utf-8');
  } catch {
    return 'empty';
  }

  if (content.trim().length === 0) return 'empty';

  const lines = content.split('\n');
  const codeLines = lines.filter((l) => {
    const t = l.trim();
    return (
      t.length > 0 &&
      !t.startsWith('//') &&
      !t.startsWith('/*') &&
      !t.startsWith('*') &&
      !t.startsWith('#')
    );
  });

  // If >80% of non-empty lines are comments, it's commented out
  const nonEmpty = lines.filter((l) => l.trim().length > 0);
  if (nonEmpty.length > 0 && codeLines.length / nonEmpty.length < 0.2) {
    return 'commented-out';
  }

  // Check for actual test assertions
  const hasAssertions =
    content.includes('describe(') ||
    content.includes('it(') ||
    content.includes('test(') ||
    content.includes('expect(') ||
    content.includes('assert') ||
    content.includes('def test_') ||
    content.includes('func Test');

  if (!hasAssertions) {
    // Could be a schema/type file named .spec.ts
    if (content.includes('export const') || content.includes('export interface')) {
      return 'schema-only';
    }
    return 'empty';
  }

  return 'active';
}

function detectTestFramework(fullPath: string): string | null {
  let content: string;
  try {
    content = fs.readFileSync(fullPath, 'utf-8').slice(0, 2000); // first 2KB
  } catch {
    return null;
  }

  if (content.includes('vitest') || content.includes("from 'vitest'")) return 'vitest';
  if (content.includes('jest') || content.includes("from '@jest'")) return 'jest';
  if (content.includes('mocha') || content.includes("from '@loopback/testlab'")) return 'mocha';
  if (content.includes('pytest') || content.includes('def test_')) return 'pytest';
  if (content.includes('testing.T')) return 'go-test';
  return null;
}

// ─── Source file discovery + risk classification ────────────────────────────

export function gatherSourceFiles(cwd: string): SourceFile[] {
  // Walker default opts apply all the filters the pre-migration
  // inline code did (and more):
  //   - exclusions via .gitignore + .dxkit-ignore + bundled defaults
  //     (covers node_modules, dist, *.d.ts, *.min.js)
  //   - autogen basename globs (*.designer.cs etc. — D028)
  //   - autogen header markers (<auto-generated>/@generated/DO NOT EDIT)
  //   - test files excluded (pack-driven test patterns — supersedes
  //     the old crude substring matchers .test/.spec/__tests__/_test/test_)
  //
  // The pre-migration inline `.swp/.pyc/.lic/.pem` filter is redundant
  // — none are source extensions, so the walker's extension filter
  // already drops them.
  const sources = walkSourceFiles(cwd);

  const files: SourceFile[] = [];
  for (const p of sources) {
    const fullPath = path.join(cwd, p);
    let lines = 0;
    try {
      const content = fs.readFileSync(fullPath, 'utf-8');
      lines = content.split('\n').length;
    } catch {
      continue;
    }
    const type = classifyFileType(p);
    const risk = classifyRisk(p, type, lines);
    files.push({
      path: p,
      lines,
      type,
      risk,
      hasMatchingTest: false, // filled in by matchTestsToSource
    });
  }
  return files;
}

function classifyFileType(filePath: string): SourceFile['type'] {
  const lower = filePath.toLowerCase();
  if (lower.includes('/controllers/') || lower.includes('/handlers/')) return 'controller';
  if (lower.includes('/services/')) return 'service';
  if (lower.includes('/interceptors/') || lower.includes('/middleware/')) return 'interceptor';
  if (lower.includes('/models/')) return 'model';
  if (lower.includes('/repositories/')) return 'repository';
  return 'other';
}

/**
 * Path prefixes for "meta-tools" — files that analyze security rather than
 * implement it. A file in `src/analyzers/security/` matches CRITICAL_PATTERNS
 * on name ("security") but it's an analyzer module, not app security code.
 * Downgrade these to their structural tier (usually LOW).
 */
const META_TOOL_PATH_PREFIXES = [/^src\/analyzers\//, /^tmp\//, /^scripts\//];

function classifyRisk(filePath: string, type: SourceFile['type'], lines: number): RiskTier {
  const lower = filePath.toLowerCase();

  // Meta-tool exception: security analyzer code matches CRITICAL_PATTERNS by
  // name alone (e.g. src/analyzers/security/gather.ts), but it's tooling, not
  // application security. Skip the pattern check so it falls through to the
  // size/type tiering below. Relative-path match — deliberately strict so we
  // don't accidentally downgrade real app code in an `analyzers` module.
  const isMetaTool = META_TOOL_PATH_PREFIXES.some((p) => p.test(filePath));

  // Security-critical files are always CRITICAL regardless of size
  if (!isMetaTool && CRITICAL_PATTERNS.some((p) => p.test(lower))) return 'critical';

  // Large controllers/services are HIGH
  if ((type === 'controller' || type === 'service') && lines > 500) return 'high';

  // Normal controllers/services/interceptors are MEDIUM
  if (type === 'controller' || type === 'service' || type === 'interceptor') return 'medium';

  // Everything else is LOW
  return 'low';
}

// ─── Match tests to source files ────────────────────────────────────────────

export function matchTestsToSource(testFiles: TestFile[], sourceFiles: SourceFile[]): void {
  // Build a set of tested source file basenames
  // e.g., "user.controller.acceptance.ts" → matches "user.controller.ts"
  const testedPatterns: string[] = [];
  for (const tf of testFiles) {
    if (tf.status !== 'active') continue;
    // Extract the base component name from the test file path
    const basename = tf.path.split('/').pop() || '';
    // Remove test markers to get the source name
    const sourceName = basename
      .replace('.test.', '.')
      .replace('.spec.', '.')
      .replace('.acceptance.', '.')
      .replace('_test.', '.')
      .replace('test_', '');
    testedPatterns.push(sourceName.toLowerCase());
  }

  for (const sf of sourceFiles) {
    const basename = (sf.path.split('/').pop() || '').toLowerCase();
    sf.hasMatchingTest = testedPatterns.some(
      (tp) =>
        basename.includes(tp.replace(/\.[^.]+$/, '')) ||
        tp.includes(basename.replace(/\.[^.]+$/, '')),
    );
  }
}
