/**
 * Detailed quality report — JSON schema + markdown formatter.
 *
 * The JSON is the canonical, agent-consumable artifact. The markdown is
 * generated from the JSON so they never diverge.
 */
import { QualityReport, QualityMetrics } from './types';
import { RankedAction, rank } from '../remediation';
import { buildSlopActions } from './actions';
import { computeSlopScore } from './index';

export interface QualityDetailedReport extends QualityReport {
  /** Schema version for agent consumers. Bump on breaking shape changes. */
  schemaVersion: string;
  /** Ranked remediation actions with simulated score deltas. */
  actions: Array<RankedAction<QualityMetrics>>;
}

export function buildQualityDetailed(report: QualityReport): QualityDetailedReport {
  const actions = rank(buildSlopActions(report.metrics), report.metrics, (m) => ({
    score: computeSlopScore(m),
  }));
  return {
    ...report,
    schemaVersion: '10c.1',
    actions,
  };
}

export function formatQualityDetailedMarkdown(
  detailed: QualityDetailedReport,
  elapsed: string,
): string {
  const L: string[] = [];
  const m = detailed.metrics;

  L.push('# Code Quality Review — Detailed');
  L.push('');
  L.push(`**Date:** ${detailed.analyzedAt.slice(0, 10)}`);
  L.push(`**Repository:** ${detailed.repo}`);
  L.push(`**Branch:** ${detailed.branch} (${detailed.commitSha})`);
  L.push(`**Slop Score:** ${detailed.slopScore}/100`);
  L.push(`**Schema version:** ${detailed.schemaVersion}`);
  L.push('');
  L.push('---');
  L.push('');

  // Ranked actions
  L.push('## Recommended Actions');
  L.push('');
  if (detailed.actions.length === 0) {
    L.push('No remediation actions suggested — slop score has no actionable deductions.');
  } else {
    L.push(
      'Actions are ranked by projected score improvement. Each delta is computed by simulating the scorer with the patched metrics.',
    );
    L.push('');
    L.push('| # | Action | Score Δ | Projected | Evidence |');
    L.push('|---|--------|--------:|----------:|----------|');
    detailed.actions.forEach((a, i) => {
      const evSuffix = a.evidence.length
        ? `${a.evidence.length} item${a.evidence.length === 1 ? '' : 's'}`
        : '—';
      L.push(
        `| ${i + 1} | ${a.title} | +${a.scoreDelta} | ${a.projectedScore}/100 | ${evSuffix} |`,
      );
    });
    L.push('');
    for (const a of detailed.actions) {
      L.push(`### ${a.title} (+${a.scoreDelta})`);
      L.push('');
      L.push(`- **ID:** \`${a.id}\``);
      L.push(`- **Baseline:** ${a.baselineScore}/100`);
      L.push(`- **Projected:** ${a.projectedScore}/100`);
      if (a.rationale) L.push(`- **Why:** ${a.rationale}`);
      if (a.evidence.length) {
        L.push('- **Evidence:**');
        for (const e of a.evidence.slice(0, 10)) {
          const loc = e.line ? `:${e.line}${e.endLine ? `-${e.endLine}` : ''}` : '';
          L.push(`  - \`${e.file}${loc}\` — ${e.message || e.rule}`);
        }
        if (a.evidence.length > 10) {
          L.push(`  - … and ${a.evidence.length - 10} more`);
        }
      }
      L.push('');
    }
  }
  L.push('---');
  L.push('');

  // Top duplicate clones
  if (m.duplication?.topClones && m.duplication.topClones.length > 0) {
    L.push('## Top Duplicate Clones');
    L.push('');
    L.push('| Lines | File A | File B |');
    L.push('|------:|--------|--------|');
    for (const c of m.duplication.topClones) {
      L.push(
        `| ${c.lines} | \`${c.a.file}:${c.a.startLine}-${c.a.endLine}\` | \`${c.b.file}:${c.b.startLine}-${c.b.endLine}\` |`,
      );
    }
    L.push('');
    L.push('---');
    L.push('');
  }

  // Top offenders
  if (m.topConsoleFiles && m.topConsoleFiles.length > 0) {
    L.push('## Files with Most Console Statements');
    L.push('');
    L.push('| File | Count |');
    L.push('|------|------:|');
    for (const f of m.topConsoleFiles) L.push(`| \`${f.file}\` | ${f.count} |`);
    L.push('');
  }

  if (m.topTodoFiles && m.topTodoFiles.length > 0) {
    L.push('## Files with Most TODO/FIXME/HACK');
    L.push('');
    L.push('| File | Count |');
    L.push('|------|------:|');
    for (const f of m.topTodoFiles) L.push(`| \`${f.file}\` | ${f.count} |`);
    L.push('');
  }

  if (m.staleFiles.length > 0) {
    L.push('## Stale Files Committed to Git');
    L.push('');
    for (const f of m.staleFiles) L.push(`- \`${f}\``);
    L.push('');
  }

  L.push('---');
  L.push('');
  L.push(`**Tools used:** ${detailed.toolsUsed.join(', ')}`);
  if (detailed.toolsUnavailable.length > 0) {
    L.push(`**Tools unavailable:** ${detailed.toolsUnavailable.join(', ')}`);
  }
  L.push(`**Analysis time:** ${elapsed}s`);
  L.push('');
  L.push(
    '*Generated by [VyuhLabs DXKit](https://www.npmjs.com/package/@vyuhlabs/dxkit) — detailed mode*',
  );
  return L.join('\n');
}
