#!/usr/bin/env bash
# Coverage threshold enforcement for pre-push hook.
#
# Reads coverage/coverage-summary.json (generated by vitest --coverage)
# and fails if line coverage is below the configured threshold.
#
# Threshold lookup order:
#   1. DXKIT_COVERAGE_THRESHOLD env var
#   2. Fallback: 15 (starting point — ratchet up as tests improve)
#
# Usage: bash scripts/check-coverage.sh

set -euo pipefail

SUMMARY="coverage/coverage-summary.json"
THRESHOLD="${DXKIT_COVERAGE_THRESHOLD:-15}"

if [ ! -f "$SUMMARY" ]; then
  echo "⚠  No coverage report at $SUMMARY — run 'npm run test:coverage' first."
  echo "   Skipping coverage threshold check."
  exit 0
fi

PCT=$(node -e "
  const d = JSON.parse(require('fs').readFileSync('$SUMMARY','utf8'));
  process.stdout.write(String(d.total?.lines?.pct ?? 0));
")

echo "Coverage: ${PCT}% (threshold: ${THRESHOLD}%)"

if node -e "process.exit(Number($PCT) < Number($THRESHOLD) ? 1 : 0)"; then
  echo "✓ Coverage meets threshold."
else
  echo "✗ Coverage ${PCT}% is below ${THRESHOLD}%. Add tests before pushing."
  exit 1
fi
