/**
 * The per-repo RUNBOOK (issue #246) — the org-rollout artifact: a short
 * markdown page, committed at the repo root, that tells a developer (or an
 * org reader on GitHub, with nothing installed) what dxkit runs in THIS
 * repo, what to do when the gate blocks, and where the escape hatches are.
 *
 * Rendered from repo truth only — the committed policy, the workflow files
 * actually present, the hooks actually installed — never from aspiration.
 * Fully offline and deterministic (no gh calls, no timestamps): the same
 * tree renders the same runbook, so `update` refreshes are meaningful diffs.
 *
 * Ownership contract (Rule 15 applied to a generated doc): the MARKER line
 * makes the file dxkit-owned — `update` regenerates it and manual edits are
 * overwritten. Deleting the marker line hands the file to the user; dxkit
 * then leaves it alone (pinned by the installer tests).
 */
import * as fs from 'fs';
import * as path from 'path';
import { readPolicyObjectSafe } from '../baseline/policy-text';
import { dxkitCli } from '../self-invocation';

export const RUNBOOK_FILENAME = 'RUNBOOK.dxkit.md';

export const RUNBOOK_MARKER =
  '<!-- managed-by-dxkit: runbook. Regenerated by `vyuh-dxkit update`; manual edits here are overwritten. Delete this comment line to take ownership of the file (dxkit will then leave it alone). -->';

interface LaneFact {
  label: string;
  file: string;
  /** Cron expression parsed out of the workflow, when present. */
  schedule?: string;
  /** Does the lane open PRs (vs push/publish only)? */
  opensPrs: boolean;
}

function readFileSafe(p: string): string {
  try {
    return fs.readFileSync(p, 'utf8');
  } catch {
    return '';
  }
}

function laneFacts(cwd: string): LaneFact[] {
  const candidates: Array<Omit<LaneFact, 'schedule'>> = [
    { label: 'Baseline refresh', file: 'dxkit-baseline-refresh.yml', opensPrs: true },
    { label: 'Dependency bump', file: 'dxkit-dep-bump.yml', opensPrs: true },
    { label: 'Remediation', file: 'dxkit-remediate.yml', opensPrs: true },
    { label: 'Report snapshots', file: 'dxkit-reports-refresh.yml', opensPrs: false },
    { label: 'Graph refresh', file: 'dxkit-graph-refresh.yml', opensPrs: false },
    { label: 'Deep-SAST refresh', file: 'dxkit-deep-sast-refresh.yml', opensPrs: false },
  ];
  const out: LaneFact[] = [];
  for (const c of candidates) {
    const abs = path.join(cwd, '.github', 'workflows', c.file);
    if (!fs.existsSync(abs)) continue;
    const cron = readFileSafe(abs).match(/cron:\s*['"]([^'"]+)['"]/);
    out.push({ ...c, schedule: cron?.[1] });
  }
  return out;
}

export function renderRunbook(cwd: string): string {
  const policy = readPolicyObjectSafe(cwd);
  const loop = policy?.loop as Record<string, unknown> | undefined;
  const preset = typeof loop?.preset === 'string' ? (loop.preset as string) : undefined;
  const checksCount = Array.isArray(policy?.checks) ? (policy.checks as unknown[]).length : 0;
  const lint = policy?.lint as Record<string, unknown> | undefined;
  const paired = Array.isArray(policy?.pairedChecks)
    ? (policy.pairedChecks as unknown[]).length
    : 0;

  const hasPrePush = fs.existsSync(path.join(cwd, '.githooks', 'pre-push'));
  const hasCi = fs.existsSync(path.join(cwd, '.github', 'workflows', 'dxkit-guardrails.yml'));
  const lanes = laneFacts(cwd);

  const gates: string[] = [];
  if (hasPrePush)
    gates.push(
      '- **On push** (local pre-push hook): the guardrail runs before your push leaves the machine.',
    );
  if (hasCi)
    gates.push(
      '- **On every PR** (CI, `dxkit-guardrails`): the same guardrail, as a required check.',
    );
  if (gates.length === 0) {
    gates.push(
      '- No dxkit gate is currently armed in this repo (no pre-push hook, no CI workflow).',
    );
  }

  const laneLines =
    lanes.length === 0
      ? ['- No scheduled lanes are installed.']
      : lanes.map(
          (l) =>
            `- **${l.label}** (\`${l.file}\`${l.schedule ? `, schedule: \`${l.schedule}\`` : ''})${l.opensPrs ? ' — lands its work only via a pull request through the same gate.' : ''}`,
        );

  return `${RUNBOOK_MARKER}

# How dxkit runs in this repository

dxkit gates **changes**, not the whole repo: findings that already existed are
recorded in a baseline and never blamed on the next pull request. Only
**net-new** problems introduced by a change can block it.

## What runs here, and when

${gates.join('\n')}

Blocking posture: ${preset ? `preset \`${preset}\`` : 'the default preset'} in
\`.dxkit/policy.json\`${checksCount > 0 ? `, plus ${checksCount} repo-specific custom check${checksCount === 1 ? '' : 's'}` : ''}${lint?.enabled ? ', plus the pack lint gate' : ''}${paired > 0 ? `, plus ${paired} paired-change rule${paired === 1 ? '' : 's'}` : ''}.

## Scheduled lanes

${laneLines.join('\n')}

## The gate blocked my PR. What now?

1. **Read the verdict** (the CI log or PR comment). It names each finding and
   its fingerprint.
2. **It's real and yours** → fix it and push. Nothing else to do.
3. **It's a false positive** → suppress it on the record, in your PR:
   \`${dxkitCli('allowlist add --fingerprint=<id> --kind=<kind> --category=false-positive --reason="<why>"')}\`
4. **Real, but not fixable now** → time-boxed deferral (it re-blocks at expiry):
   \`${dxkitCli('allowlist defer <fingerprint> --reason="<why later>" --expires=+14d')}\`
5. **The verdict is CANNOT GATE** → not your change's fault; the baseline needs
   a refresh on the repo side. Tell whoever maintains this repo's dxkit setup.

Never re-create the baseline from a feature branch to clear a block — that
absorbs your finding into the record for everyone.

## Escape hatches, on the record

Every suppression is typed (\`false-positive\`, \`test-fixture\`,
\`mitigated-externally\`, \`accepted-risk\`, \`deferred\`), carries a required
reason, and is auditable later (\`${dxkitCli('allowlist audit')}\`). Deferrals
expire and re-block; they are loans, not write-offs.

## Verify and learn

- \`${dxkitCli('doctor')}\` — is the setup healthy here, and what does it recommend?
- \`${dxkitCli('learn')}\` — the full capability guide + this repo's live status as one offline HTML page (\`--serve\` adds a local assistant).
- \`${dxkitCli('capabilities --markdown')}\` — this catalog in pasteable markdown.
`;
}
