/**
 * Licenses analyzer — public API.
 *
 * Produces a per-package license inventory by dispatching the LICENSES
 * capability across every active language pack. Output formats:
 *
 *   - `formatLicensesMarkdown(report)` — table markdown for
 *     `.ai/reports/licenses-<date>.md` and PR comments.
 *   - JSON via the CLI's `--json` flag — envelope pass-through with
 *     the added summary + repo metadata.
 *   - XLSX — 15-column drop-in for the customer's spreadsheet
 *     workflow; lands in Phase 10h.2.2 via `exceljs`.
 */

import * as path from 'path';
import { detect } from '../../detect';
import { run } from '../tools/runner';
import { gatherLicensesResult } from './gather';
import type { LicensesReport } from './types';

export type { LicensesReport } from './types';

export interface AnalyzeLicensesOptions {
  verbose?: boolean;
}

export async function analyzeLicenses(
  repoPath: string,
  _options: AnalyzeLicensesOptions = {},
): Promise<LicensesReport> {
  const stack = detect(repoPath);
  const envelope = await gatherLicensesResult(repoPath);

  const findings = envelope?.findings ?? [];
  const byLicense: Record<string, number> = {};
  let unknownCount = 0;
  for (const f of findings) {
    byLicense[f.licenseType] = (byLicense[f.licenseType] ?? 0) + 1;
    if (f.licenseType === 'UNKNOWN' || f.licenseType.length === 0) unknownCount++;
  }

  const toolsUsed = envelope ? envelope.tool.split(', ').filter((t) => t.length > 0) : [];

  return {
    repo: stack.projectName || path.basename(repoPath),
    analyzedAt: new Date().toISOString(),
    commitSha: run('git rev-parse --short HEAD 2>/dev/null', repoPath),
    branch: run('git rev-parse --abbrev-ref HEAD 2>/dev/null', repoPath),
    schemaVersion: '1',
    summary: {
      totalPackages: findings.length,
      byLicense,
      unknownCount,
    },
    findings,
    toolsUsed,
    toolsUnavailable: [],
  };
}

export function formatLicensesReport(report: LicensesReport, elapsed: string): string {
  const L: string[] = [];

  L.push('# License Inventory Report');
  L.push('');
  L.push(`**Date:** ${report.analyzedAt.slice(0, 10)}`);
  L.push(`**Repository:** ${report.repo}`);
  L.push(`**Branch:** ${report.branch} (${report.commitSha})`);
  L.push('');
  L.push('---');
  L.push('');

  // Summary
  L.push('## Summary');
  L.push('');
  L.push(
    `**${report.summary.totalPackages} packages** across ${Object.keys(report.summary.byLicense).length} distinct license types.`,
  );
  if (report.summary.unknownCount > 0) {
    L.push('');
    L.push(
      `> ⚠️ ${report.summary.unknownCount} package(s) have no detected license — review before shipping.`,
    );
  }
  L.push('');

  // Breakdown by license
  L.push('## License Distribution');
  L.push('');
  L.push('| License | Count |');
  L.push('|---------|-------|');
  const sorted = Object.entries(report.summary.byLicense).sort((a, b) => b[1] - a[1]);
  for (const [lic, count] of sorted) {
    L.push(`| ${lic} | ${count} |`);
  }
  L.push('');
  L.push('---');
  L.push('');

  // Findings table
  L.push('## Packages');
  L.push('');
  if (report.findings.length === 0) {
    L.push(
      '_No packages detected. Ensure the project has a resolved dependency tree (e.g. `npm install`, `pip install`, `go mod download`, `cargo build`, `dotnet restore`) before running this analyzer._',
    );
  } else {
    L.push('| Package | Version | License | Supplier |');
    L.push('|---------|---------|---------|----------|');
    const rows = [...report.findings].sort((a, b) => a.package.localeCompare(b.package));
    for (const f of rows) {
      const supplier = (f.supplier || '').replace(/\|/g, '\\|');
      L.push(`| \`${f.package}\` | ${f.version} | ${f.licenseType} | ${supplier} |`);
    }
  }
  L.push('');
  L.push('---');
  L.push('');

  // Footer
  L.push(`**Tools used:** ${report.toolsUsed.join(', ') || '(none)'}`);
  L.push(`**Analysis time:** ${elapsed}s`);
  L.push('');
  L.push('*Generated by [VyuhLabs DXKit](https://www.npmjs.com/package/@vyuhlabs/dxkit)*');

  return L.join('\n');
}
