/**
 * Generic tool runner -- uses grep, find, wc, git.
 * Works on any Unix machine with no external dependencies.
 * This is Layer 0: always available.
 */
import * as fs from 'fs';
import * as path from 'path';
import { HealthMetrics } from '../types';
import { isAutogeneratedByHeader } from './autogen-header';
import { run, countLines, fileExists } from './runner';
import { getFindExcludeFlags, isExcludedPath } from './exclusions';
import {
  allAutogenSourcePatterns,
  allDocCommentPatterns,
  allSourceExtensions,
  allTlsBypassPatterns,
  splitTestFilePatterns,
} from '../../languages';

// D056 (2.4.7): the pre-fix `| grep -v node_modules | grep -v dist`
// shell pipe only filtered two hardcoded basenames — every other
// exclusion (project `.gitignore`, `.dxkit-ignore`, the bundled
// defaults' 24-entry set) was silently ignored by registry-driven
// greps. Post-D056, every grep helper in this module parses results
// in JS and post-filters via `isExcludedPath()`, which is the single
// source of truth for "should this path be excluded?" — the same
// predicate that grep-secrets.ts and quality/gather.ts already use.

/**
 * D072 (2.4.7): match the post-filter set `gatherGenericMetrics` uses
 * for `sourceFiles`. Pre-D072 the registry-greps applied
 * `isExcludedPath` (D056) but NOT the autogen-basename glob (D028) or
 * the autogen-header content marker (D051). Result: docCommentFiles
 * could exceed sourceFiles (designer.cs files with XML-doc comments
 * counted in the numerator but not the denominator → 104% docRatio
 * on dpl-studio).
 *
 * This is the same gather-disagreement class as D055/D057. Layer
 * ownership: every field claiming "files containing X among source
 * files" must share `sourceFiles`'s definition of "source file." The
 * predicate here is the canonical "is this a counted source file?"
 * single source of truth. Class-fix is `walkSourceFiles` (G_v4_7)
 * in 2.4.8 — until then, each grep caller funnels through this.
 */
function isAutogenSourceBasename(relPath: string, autogenPatterns: string[]): boolean {
  const base = relPath.split('/').pop() ?? '';
  for (const pat of autogenPatterns) {
    // Patterns are simple basename globs (`*.designer.cs`, `*.g.cs`, ...)
    if (matchesBasenameGlob(pat, base)) return true;
  }
  return false;
}

function matchesBasenameGlob(pat: string, base: string): boolean {
  if (!pat.includes('*') && !pat.includes('?')) return pat === base;
  const regex = new RegExp(
    '^' +
      pat
        .replace(/[.+^${}()|[\]\\]/g, '\\$&')
        .replace(/\*/g, '.*')
        .replace(/\?/g, '.') +
      '$',
    'i',
  );
  return regex.test(base);
}

/**
 * Canonical "include this path in source-file metrics?" predicate. Used
 * by every grep caller in this module so doc-comment / TLS-bypass /
 * eval counts share the same source-file definition as `sourceFiles`.
 */
function isCountedSourceFile(cwd: string, relPath: string, autogenPatterns: string[]): boolean {
  if (isExcludedPath(cwd, relPath)) return false;
  if (isAutogenSourceBasename(relPath, autogenPatterns)) return false;
  if (isAutogeneratedByHeader(path.join(cwd, relPath))) return false;
  return true;
}

/**
 * Build the shared `grep --include='*.<ext>' ...` flag list from the
 * pack registry. Used by every registry-driven grep helper in this
 * module (D027 doc-comments, D034 TLS-bypass) so adding a new pack
 * auto-extends the search scope.
 */
function sourceIncludeFlags(): string {
  return allSourceExtensions()
    .map((ext) => `--include='*${ext}'`)
    .join(' ');
}

/**
 * Run a registry-derived grep alternation against every pack's
 * source extensions and return either the matching-file count
 * (`mode: 'l'`, like `grep -rlE`) or the matching-line count
 * (`mode: 'n'`, like `grep -rnE | wc -l`).
 *
 * Builds a temp pattern file (one regex per line — grep -Ef syntax)
 * to avoid shell-escaping issues when patterns contain single
 * quotes, double quotes, `::`, etc. (Python docstrings, Ruby
 * `OpenSSL::SSL::VERIFY_NONE` etc.). Short-circuits to 0 when no
 * pack declares any patterns.
 */
function countRegistryGrep(cwd: string, patterns: string[], mode: 'l' | 'n'): number {
  if (patterns.length === 0) return 0;
  const includeFlags = sourceIncludeFlags();
  const autogenPatterns = allAutogenSourcePatterns();
  const patternFile = `/tmp/dxkit-grep-${Date.now()}-${Math.random().toString(36).slice(2)}.pat`;
  fs.writeFileSync(patternFile, patterns.join('\n'));
  try {
    const flag = mode === 'l' ? '-rlEf' : '-rnEf';
    const raw = run(`grep ${flag} '${patternFile}' ${includeFlags} . 2>/dev/null`, cwd);
    if (!raw) return 0;
    let count = 0;
    for (const line of raw.split('\n')) {
      if (!line) continue;
      // Mode 'l': line IS the path. Mode 'n': line is `path:lineno:content`.
      const filePath = (mode === 'l' ? line : line.split(':', 1)[0]).replace(/^\.\//, '');
      if (!filePath) continue;
      if (!isCountedSourceFile(cwd, filePath, autogenPatterns)) continue;
      count++;
    }
    return count;
  } finally {
    try {
      fs.unlinkSync(patternFile);
    } catch {
      /* ignore */
    }
  }
}

/**
 * Count files containing at least one doc-comment marker (D027 /
 * 2.4.7). Per-language regex shapes contributed by each pack's
 * `docCommentPatterns`.
 */
function countDocCommentFiles(cwd: string): number {
  return countRegistryGrep(cwd, allDocCommentPatterns(), 'l');
}

/**
 * Count lines containing a TLS / cert-validation bypass idiom
 * (D034 / 2.4.7). Per-language regex shapes contributed by each
 * pack's `tlsBypassPatterns`. Counts lines (not files) because a
 * single file may carry multiple distinct bypass points — each one
 * is a separate finding for the Security score.
 */
function countTlsBypassLines(cwd: string): number {
  return countRegistryGrep(cwd, allTlsBypassPatterns(), 'n');
}

/**
 * Reliable grep count that avoids shell escaping issues by writing pattern to a temp file.
 * D056 (2.4.7): post-filters via `isExcludedPath()` so project
 * `.dxkit-ignore` + `.gitignore` apply (was hardcoded `node_modules`
 * + `dist` + `__pycache__` + `.d.ts` only).
 */
function grepCount(cwd: string, pattern: string, includes: string[]): number {
  const patternFile = `/tmp/dxkit-grep-${Date.now()}-${Math.random().toString(36).slice(2)}.pat`;
  fs.writeFileSync(patternFile, pattern);
  const includeFlags = includes.map((i) => `--include='${i}'`).join(' ');
  const raw = run(`grep -rnEf '${patternFile}' ${includeFlags} . 2>/dev/null`, cwd);
  try {
    fs.unlinkSync(patternFile);
  } catch {
    /* ignore */
  }
  if (!raw) return 0;
  const autogenPatterns = allAutogenSourcePatterns();
  let count = 0;
  for (const line of raw.split('\n')) {
    if (!line) continue;
    const filePath = line.split(':', 1)[0].replace(/^\.\//, '');
    if (!filePath) continue;
    if (!isCountedSourceFile(cwd, filePath, autogenPatterns)) continue;
    count++;
  }
  return count;
}

// EXCLUDE moved inside gatherGenericMetrics() — must be computed per-cwd now
// so it picks up project-specific .gitignore / .dxkit-ignore entries.

// Pack-driven find expressions (Phase 10i.0-LP.3). Replaces the
// pre-LP hardcoded extension/pattern lists with iteration over the
// language registry. Adding a 6th pack auto-extends both expressions.
//
// Behavior expansions vs pre-LP.3 (both more correct than before):
//   - `.mjs`/`.cjs` now counted as source files (TypeScript pack
//     declared them in `sourceExtensions`; the legacy hardcoded list
//     missed them).
//   - Rust integration tests under `tests/*.rs` now counted as test
//     files (Rust pack declared `tests/*.rs` as a path-anchored
//     pattern; the legacy used only `-name` and skipped path patterns).
const SOURCE_EXTS = `\\( ${allSourceExtensions()
  .map((e) => `-name "*${e}"`)
  .join(' -o ')} \\)`;

// D028 (2.4.7): `find` expression that EXCLUDES auto-generated source
// files. Built by unioning every active pack's
// `autogeneratedSourcePatterns` (csharp's `*.designer.cs`, go's
// `*.pb.go`, java's `*Generated.java`, etc.). Empty string when no
// pack declares any autogen patterns — `find` treats an absent
// `-not -name` clause as "no exclusions" (consistent with pre-D028
// behavior for packs that haven't yet adopted autogen filtering).
const AUTOGEN_EXCLUDES = (() => {
  const patterns = allAutogenSourcePatterns();
  if (patterns.length === 0) return '';
  return patterns.map((p) => `-not -name "${p}"`).join(' ');
})();

const TEST_PATTERNS = (() => {
  const { nameOnly, pathAnchored } = splitTestFilePatterns();
  const nameClauses = nameOnly.map((p) => `-name "${p}"`);
  const pathClauses = pathAnchored.map((p) => `-path "*/${p}"`);
  return `\\( ${[...nameClauses, ...pathClauses].join(' -o ')} \\)`;
})();

/**
 * Resolve the git toplevel for `cwd`. D026 (2.4.7): cross-cutting repo
 * artifacts (`.github/`, `README.md`, `CONTRIBUTING.md`, `Makefile`,
 * `.env.example`, etc.) conventionally live at the repo root, not in
 * the subdirectory a user happens to scan. dpl-studio's baseline F8:
 * customer ran `dxkit health Code/Source/`; both Documentation and DX
 * dimensions returned 0/100 because none of those probes found
 * matches in `Code/Source/`. The fix scopes those probes to the
 * git toplevel.
 *
 * Returns `cwd` unchanged when `git rev-parse --show-toplevel` fails
 * (not in a git repo, or git missing) so non-git workflows keep
 * working — they just don't get the toplevel-scoped improvement.
 */
function resolveGitToplevel(cwd: string): string {
  const top = run('git rev-parse --show-toplevel 2>/dev/null', cwd).trim();
  return top.length > 0 ? top : cwd;
}

/** Gather metrics using only built-in Unix tools. */
export function gatherGenericMetrics(cwd: string): Partial<HealthMetrics> {
  const EXCLUDE = getFindExcludeFlags(cwd);
  // D026 (2.4.7): repo-level artifacts probed from git toplevel; code-
  // level metrics (source-file counts, hygiene grep, semgrep) stay
  // scoped to `cwd` so analyzing a subdirectory still measures that
  // subdir's code quality.
  const repoRoot = resolveGitToplevel(cwd);

  // File counts — D028 (2.4.7): exclude auto-generated sources from
  // source-file counts AND from the wc pass that drives totalLines /
  // filesOver500Lines / largestFileLines. Visual Studio designer.cs,
  // T4-generated *.g.cs, etc. inflate every per-file metric otherwise.
  // Test-file counts INCLUDE autogen filters too — autogen test files
  // are rare but possible (Roslyn-generated test scaffolds).
  // `rawSourceFiles` is the find-only count (filename-based exclusions
  // only). The post-header-filter count below replaces this once the
  // wc pass populates `filteredFiles`. Fallback path: if wc fails
  // (e.g. exceeds 2-min timeout on enormous trees), we surface
  // rawSourceFiles rather than zero.
  const rawSourceFiles = countLines(
    `find . -type f ${SOURCE_EXTS} ${AUTOGEN_EXCLUDES} ${EXCLUDE}`,
    cwd,
  );
  const testFiles = countLines(
    `find . -type f ${TEST_PATTERNS} ${AUTOGEN_EXCLUDES} ${EXCLUDE}`,
    cwd,
  );
  const testDirFiles = countLines(
    `find . -type f ${SOURCE_EXTS} ${AUTOGEN_EXCLUDES} ${EXCLUDE} \\( -path "*/__tests__/*" -o -path "*/tests/*" -o -path "*/test/*" \\) 2>/dev/null`,
    cwd,
  );

  // Total lines, largest file, files over 500 — single find+xargs wc pass
  const wcRaw = run(
    `find . -type f ${SOURCE_EXTS} ${AUTOGEN_EXCLUDES} ${EXCLUDE} -print0 2>/dev/null | xargs -0 wc -l 2>/dev/null`,
    cwd,
    120000,
  );

  // 2.4.7: collect every file's line count so we can both (a) filter
  // header-marked autogen files post-wc and (b) surface a top-10
  // ranking, not just the single biggest. Sorted + capped below.
  const rawFiles: Array<{ path: string; lines: number }> = [];
  let rawTotalLines = 0;

  if (wcRaw) {
    for (const line of wcRaw.split('\n')) {
      const m = line.trim().match(/^(\d+)\s+(.+)$/);
      if (!m) continue;
      const lines = parseInt(m[1]);
      const file = m[2];
      if (file === 'total') {
        rawTotalLines = lines;
      } else {
        rawFiles.push({ path: file, lines });
      }
    }
  }

  // D028 extension (2.4.7): filter out files whose first 2KB contains
  // a `<auto-generated>` / `@generated` / `Code generated by` / etc.
  // marker. Catches hand-named generated files (e.g. SAP B1 wrappers
  // `OWTQ.cs`, `OPCH.cs` on dpl-studio — 30 files × 11,517 lines each
  // that pre-D028-header inflated every per-file metric).
  // Falls through harmlessly when no markers are present.
  const filteredFiles = rawFiles.filter(
    (f) => !isAutogeneratedByHeader(path.join(cwd, f.path.replace(/^\.\//, ''))),
  );

  let totalLines = 0;
  let largestFileLines = 0;
  let largestFilePath = '';
  let filesOver500Lines = 0;
  for (const f of filteredFiles) {
    totalLines += f.lines;
    if (f.lines > largestFileLines) {
      largestFileLines = f.lines;
      largestFilePath = f.path;
    }
    if (f.lines > 500) filesOver500Lines++;
  }
  // Single-file case: xargs wc skips the "total" line. Fall back to
  // the lone file's count so totalLines isn't 0.
  if (totalLines === 0 && filteredFiles.length === 1) totalLines = filteredFiles[0].lines;
  // Suppress an unused-var warning when rawTotalLines isn't read elsewhere.
  void rawTotalLines;

  // sourceFiles reflects the post-header-filter count when wc ran
  // successfully. Falls back to rawSourceFiles (find-only) if wc
  // produced no output — better to over-report than to claim zero.
  const sourceFiles = wcRaw ? filteredFiles.length : rawSourceFiles;

  const largestFiles = [...filteredFiles].sort((a, b) => b.lines - a.lines).slice(0, 10);

  // Console/debug statement count -- use grepCount helper for reliability
  const jsConsoleCount = grepCount(cwd, 'console\\.(log|error|warn)', ['*.ts', '*.tsx', '*.js']);
  const pyPrintCount = grepCount(cwd, '\\bprint\\(', ['*.py']);
  const goPrintCount = grepCount(cwd, 'fmt\\.Print', ['*.go']);
  const consoleLogCount = jsConsoleCount + pyPrintCount + goPrintCount;

  // TypeScript ": any" count
  const anyTypeCount = grepCount(cwd, ': any', ['*.ts', '*.tsx']);

  // Documentation — D026 (2.4.7): probe from repo root, not from cwd.
  // dpl-studio's `Code/Source/` doesn't have README.md/etc.; the repo
  // root does. docCommentFiles stays cwd-scoped because it counts
  // source-file doc-comment density inside whatever subtree the user
  // chose to analyze.
  const readmeExists = fileExists(repoRoot, 'README.md', 'readme.md');
  const readmeLines =
    parseInt(run("wc -l README.md 2>/dev/null | awk '{print $1}'", repoRoot)) || 0;
  // D027 (2.4.7): doc-comment regex + include flags both derive from
  // the language pack registry. Pre-D027 both were hardcoded to
  // TS/Python/Go shapes; csharp `///`, rust `///|//!`, kotlin/java
  // `/**`, ruby `##` were never counted, pinning Documentation scores
  // at 0/100 for any project outside that initial 3-pack set.
  const docCommentFiles = countDocCommentFiles(cwd);
  const apiDocsExist = fileExists(
    repoRoot,
    'openapi.json',
    'openapi.yaml',
    'swagger.json',
    'swagger.yaml',
  );
  const architectureDocsExist = fileExists(repoRoot, 'ARCHITECTURE.md', 'docs/', 'ADR/', 'adr/');
  const contributingExists = fileExists(repoRoot, 'CONTRIBUTING.md');
  const changelogExists = fileExists(repoRoot, 'CHANGELOG.md', 'CHANGES.md');

  // Security — secret scanning lives entirely under the SECRETS capability
  // (gitleaks, 800+ patterns). The 7-pattern grep fallback that used to
  // live here was deleted in Phase 10e.C.7 along with the legacy
  // `secretFindings` / `secretDetails` fields. When gitleaks is absent
  // the report surfaces that fact through `toolsUnavailable` and the
  // capability envelope is simply absent.
  // D056 (2.4.7): routed through grepCount so `.dxkit-ignore` /
  // `.gitignore` / bundled defaults all apply. lp-recipe-ok: see
  // D033 — eval() is JS/Py-affinity; Rust/Java/Kotlin/C# need
  // separate per-pattern language scoping.
  const evalCount = grepCount(cwd, '\\beval\\(', ['*.ts', '*.js', '*.py']);

  const privateKeyFiles = countLines(
    `find . \\( -name "*.key" -o -name "*.pem" \\) ${EXCLUDE} 2>/dev/null`,
    cwd,
  );
  const envFilesInGit = countLines('git ls-files .env .env.* 2>/dev/null', cwd);
  // D034 (2.4.7): TLS-bypass detection derives from the pack
  // registry. Pre-D034 only Node-shaped (`NODE_TLS_REJECT_UNAUTHORIZED`,
  // `rejectUnauthorized: false`) and Python-shaped (`VERIFY_SSL`)
  // idioms matched against a hardcoded `*.ts/*.js/*.py` include
  // list. csharp `ServerCertificateValidationCallback`, go
  // `InsecureSkipVerify`, rust `danger_accept_invalid_certs`,
  // java/kotlin `TrustAllX509TrustManager`, ruby `OpenSSL::SSL::VERIFY_NONE`
  // were never detected.
  const tlsDisabledCount = countTlsBypassLines(cwd);

  // Maintainability
  const controllers = countLines(
    `find . \\( -path "*/controllers/*" -name "*.ts" -o -path "*/handlers/*" -name "*.go" -o -path "*/views/*" -name "*.py" \\) ${EXCLUDE} 2>/dev/null`,
    cwd,
  );
  const models = countLines(
    `find . -path "*/models/*" -type f ${SOURCE_EXTS} ${EXCLUDE} 2>/dev/null`,
    cwd,
  );
  const directories = countLines(`find . -type d ${EXCLUDE} 2>/dev/null`, cwd);

  // Developer Experience — D026 (2.4.7): probe repo root. CI/Docker/
  // pre-commit/Makefile/env-example conventionally live at the repo
  // root. dpl-studio: pre-D026 these all returned 0 when run from
  // `Code/Source/` because `.github/workflows/` etc. live one level up.
  const ciConfigCount = countLines(
    'find .github/workflows -name "*.yml" -o -name "*.yaml" 2>/dev/null; ls .gitlab-ci.yml Jenkinsfile .circleci/config.yml 2>/dev/null',
    repoRoot,
  );
  const dockerConfigCount = countLines(
    'ls Dockerfile docker-compose.yml docker-compose.yaml .devcontainer/devcontainer.json 2>/dev/null',
    repoRoot,
  );
  const precommitConfigCount = countLines(
    'ls -d .husky .pre-commit-config.yaml .git/hooks/pre-commit 2>/dev/null',
    repoRoot,
  );
  const makefileExists = fileExists(repoRoot, 'Makefile', 'justfile', 'Taskfile.yml');
  const envExampleExists = fileExists(repoRoot, '.env.example', '.env.sample', '.env.template');

  // Coverage config — D026 (2.4.7): also repo-root-scoped. Most test
  // runners look for these at the project root; scanning a subdirectory
  // shouldn't make dxkit forget the test setup exists at the top.
  const coverageConfigExists = fileExists(
    repoRoot,
    '.nycrc',
    '.nycrc.json',
    '.c8rc',
    '.c8rc.json',
    'jest.config.js',
    'jest.config.ts',
    'vitest.config.ts',
    'vitest.config.js',
    '.coveragerc',
    'setup.cfg',
    'pytest.ini',
  );

  return {
    sourceFiles,
    testFiles: testFiles + testDirFiles,
    totalLines,
    coverageConfigExists,
    filesOver500Lines,
    largestFileLines,
    largestFilePath,
    largestFiles,
    consoleLogCount,
    anyTypeCount,
    readmeExists,
    readmeLines,
    docCommentFiles,
    apiDocsExist,
    architectureDocsExist,
    contributingExists,
    changelogExists,
    evalCount,
    privateKeyFiles,
    envFilesInGit,
    tlsDisabledCount,
    controllers,
    models,
    directories,
    ciConfigCount,
    dockerConfigCount,
    precommitConfigCount,
    makefileExists,
    envExampleExists,
    toolsUsed: ['grep', 'find', 'wc', 'git'],
    toolsUnavailable: [],
  };
}
