/**
 * G_v4_7 (2.4.7) — canonical source-file walker + line-match counter.
 *
 * Every consumer that needs "the list of source files in this repo"
 * routes through `walkSourceFiles`. Every consumer that needs "how
 * many lines match pattern P across source files" routes through
 * `countLineMatches`. ONE walker, ONE counter — replaces the four
 * site-specific implementations that were drifting (D075, D079).
 *
 * NEVER shells out. Pre-fix `grep -rEf <pat> --include=*.js .` on
 * web-client produced 67MB of stdout (matched minified .js content)
 * and silently failed with ENOBUFS — `run()`'s 64MB ceiling truncated
 * to empty string, `consoleLogCount` reported 0 when reality was ~1370
 * (D082/D083). Walking the curated set in JS and scanning each file's
 * lines in-process eliminates the maxBuffer ceiling entirely.
 *
 * Filter pipeline (per file encountered):
 *   1. Directory prune at entry: `isExcludedPath(cwd, relDir)` → never descend.
 *   2. Extension filter (default `allSourceExtensions()`).
 *   3. Path-pattern filter: `isExcludedPath(cwd, relPath)`.
 *   4. Autogen basename glob (`*.designer.cs`, `*.pb.go`, …).
 *   5. Autogen header marker (first 2KB).
 *   6. Test-file filter (skip unless `includeTests: true`).
 *   7. Pack scoping (when `opts.packId` set).
 */
import * as fs from 'fs';
import * as path from 'path';
import { isExcludedPath } from './exclusions';
import { isAutogeneratedByHeader } from './autogen-header';
import {
  allAutogenSourcePatterns,
  allSourceExtensions,
  allTestFilePatterns,
  getLanguage,
} from '../../languages';
import type { LanguageId } from '../../types';

// ─── walkSourceFiles ────────────────────────────────────────────────────────

export interface WalkOpts {
  /** Restrict to specific extensions (e.g. `['.ts', '.tsx']`). Default:
   *  union across every registered language pack. */
  extensions?: string[];

  /** Include test files? Default: false. Test files are matched by
   *  `allTestFilePatterns()` — basename globs (`*.test.ts`) and
   *  path-anchored patterns (`tests/*.rs`). */
  includeTests?: boolean;

  /** Include auto-generated files (basename glob + 2KB header marker)?
   *  Default: false. Matches the post-D028 canonical "counted source
   *  file" predicate. */
  includeAutogen?: boolean;

  /** Apply `.gitignore` + `.dxkit-ignore` + bundled defaults? Default:
   *  true. Set false only for paths that genuinely need a raw FS view. */
  respectIgnore?: boolean;

  /** Restrict to one language pack's `sourceExtensions`. Default: all. */
  packId?: LanguageId;
}

interface ResolvedOpts {
  extensions: Set<string>;
  includeTests: boolean;
  includeAutogen: boolean;
  respectIgnore: boolean;
  autogenBasenamePatterns: string[];
  testFilePatterns: { nameOnly: string[]; pathAnchored: string[] };
}

/** Cache: one entry per (cwd, opts-fingerprint). Cleared via
 *  `clearWalkCache()`. Same memo pattern as `loadExclusions`. */
const walkCache = new Map<string, string[]>();

export function clearWalkCache(): void {
  walkCache.clear();
}

/**
 * Walk the source tree rooted at `cwd` and return relative POSIX paths
 * (no leading `./`) sorted for determinism. Returns `[]` for non-
 * existent or non-directory roots — never throws.
 */
export function walkSourceFiles(cwd: string, opts: WalkOpts = {}): string[] {
  const resolved = resolveOpts(opts);
  const cacheKey = `${cwd}\0${cacheKeyFor(opts)}`;
  const hit = walkCache.get(cacheKey);
  if (hit) return hit;

  const out: string[] = [];
  try {
    walkDir(cwd, '', resolved, out);
  } catch {
    // I/O error mid-walk: surface what we found so far.
  }
  out.sort();
  walkCache.set(cacheKey, out);
  return out;
}

function resolveOpts(opts: WalkOpts): ResolvedOpts {
  // Precedence: explicit `extensions` > pack-scoped extensions > all packs.
  let exts: string[];
  if (opts.extensions) {
    exts = opts.extensions;
  } else if (opts.packId) {
    exts = getLanguage(opts.packId)?.sourceExtensions ?? [];
  } else {
    exts = allSourceExtensions();
  }
  return {
    extensions: new Set(exts.map((e) => (e.startsWith('.') ? e : `.${e}`))),
    includeTests: opts.includeTests ?? false,
    includeAutogen: opts.includeAutogen ?? false,
    respectIgnore: opts.respectIgnore ?? true,
    autogenBasenamePatterns: opts.includeAutogen ? [] : allAutogenSourcePatterns(),
    testFilePatterns: splitTestPatterns(allTestFilePatterns()),
  };
}

function cacheKeyFor(opts: WalkOpts): string {
  return JSON.stringify([
    opts.extensions ?? null,
    opts.includeTests ?? false,
    opts.includeAutogen ?? false,
    opts.respectIgnore ?? true,
    opts.packId ?? null,
  ]);
}

function walkDir(cwd: string, relDir: string, opts: ResolvedOpts, out: string[]): void {
  const absDir = relDir ? path.join(cwd, relDir) : cwd;
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(absDir, { withFileTypes: true });
  } catch {
    return;
  }

  for (const ent of entries) {
    const relPath = relDir ? `${relDir}/${ent.name}` : ent.name;

    if (ent.isDirectory()) {
      // Prune at directory boundary so node_modules/ etc. are never
      // descended into. Massive perf win on minified-JS-heavy repos.
      if (opts.respectIgnore && isExcludedPath(cwd, relPath)) continue;
      // Skip dot-directories ALWAYS (.git, .vscode, .idea, .dxkit…).
      // These rarely appear in `.gitignore` but are universally noise.
      if (ent.name.startsWith('.')) continue;
      walkDir(cwd, relPath, opts, out);
      continue;
    }

    if (!ent.isFile()) continue;

    // Extension gate first (cheap).
    const ext = path.extname(ent.name);
    if (!opts.extensions.has(ext)) continue;

    // Pack scoping (cheap — done after extension because packId is rare).
    if (opts.respectIgnore && isExcludedPath(cwd, relPath)) continue;

    // Test-file filter.
    if (!opts.includeTests && isTestFile(relPath, ent.name, opts.testFilePatterns)) continue;

    // Autogen basename glob.
    if (!opts.includeAutogen && matchesAnyBasenameGlob(ent.name, opts.autogenBasenamePatterns)) {
      continue;
    }

    // Autogen header marker (most expensive — reads first 2KB).
    if (!opts.includeAutogen && isAutogeneratedByHeader(path.join(absDir, ent.name))) continue;

    out.push(relPath);
  }
}

function isTestFile(
  relPath: string,
  basename: string,
  patterns: { nameOnly: string[]; pathAnchored: string[] },
): boolean {
  for (const pat of patterns.nameOnly) {
    if (matchesBasenameGlob(pat, basename)) return true;
  }
  for (const pat of patterns.pathAnchored) {
    // Path-anchored patterns like `tests/*.rs` — match against the
    // relative path. Convert glob to regex (path-segment aware).
    if (matchesPathGlob(pat, relPath)) return true;
  }
  return false;
}

function matchesAnyBasenameGlob(basename: string, patterns: string[]): boolean {
  for (const pat of patterns) {
    if (matchesBasenameGlob(pat, basename)) return true;
  }
  return false;
}

function matchesBasenameGlob(pat: string, base: string): boolean {
  if (!pat.includes('*') && !pat.includes('?')) return pat === base;
  const regex = globToRegex(pat, false);
  return regex.test(base);
}

function matchesPathGlob(pat: string, relPath: string): boolean {
  // `tests/*.rs` should match `tests/foo.rs` AND `crate/tests/foo.rs`
  // (path-anchored "anywhere in tree"). Mirrors find's `-path "*/x"`.
  const regex = globToRegex(pat, true);
  return regex.test(relPath);
}

function globToRegex(pat: string, allowSlash: boolean): RegExp {
  const star = allowSlash ? '.*' : '[^/]*';
  const body = pat
    .replace(/[.+^${}()|[\]\\]/g, '\\$&')
    .replace(/\*/g, star)
    .replace(/\?/g, allowSlash ? '.' : '[^/]');
  // Path-anchored: allow optional leading directory segments.
  return new RegExp(allowSlash ? `(?:^|/)${body}$` : `^${body}$`, 'i');
}

function splitTestPatterns(patterns: string[]): {
  nameOnly: string[];
  pathAnchored: string[];
} {
  const nameOnly: string[] = [];
  const pathAnchored: string[] = [];
  for (const p of patterns) {
    if (p.includes('/')) pathAnchored.push(p);
    else nameOnly.push(p);
  }
  return { nameOnly, pathAnchored };
}

// ─── countLineMatches ───────────────────────────────────────────────────────

export interface CountOpts {
  /** 'files' = count of files with ≥1 match. 'lines' = total match
   *  count across all lines. Default: 'lines'. */
  mode?: 'files' | 'lines';

  /** Skip lines whose match falls on a comment line. Default: false.
   *  D074 closure — pre-fix, line-counters matched a commented-out
   *  occurrence of a target call the same as a live one and inflated
   *  counts 2x+ on commented-code-heavy codebases (platform: 1578
   *  reported / 733 active for the JS print-statement family).
   *
   *  Per-file comment marker chosen by extension:
   *    .ts/.tsx/.js/.jsx/.go/.rs/.java/.kt/.kts/.cs/.cpp/.c/.h/.hpp/.swift  -> slash-style
   *    .py/.rb/.sh/.yml/.yaml/.toml                                          -> hash-style
   *  Files with no known mapping are scanned as-is (no comment filter). */
  skipComments?: boolean;

  /** Return top-N (by match count) offender list. Default: 0 (skip). */
  perFileTopN?: number;
}

export interface CountResult {
  /** Sum of matches across all walked files. */
  lines: number;
  /** Count of files with ≥1 match. */
  files: number;
  /** Top-N offenders. Empty unless `perFileTopN > 0`. */
  perFile: Array<{ file: string; count: number }>;
}

/**
 * Read each file once, scan in-process. Pass `patterns` as compiled
 * regexes for repeated use, or as strings (compiled here with global
 * flag). Each line is tested against the alternation; multiple
 * patterns are unioned via `RegExp` `|` — pass them pre-merged for
 * best performance.
 */
export function countLineMatches(
  cwd: string,
  files: string[],
  patterns: RegExp[] | string[],
  opts: CountOpts = {},
): CountResult {
  const mode = opts.mode ?? 'lines';
  const skipComments = opts.skipComments ?? false;
  const topN = opts.perFileTopN ?? 0;

  const compiled = compilePatterns(patterns);
  if (compiled.length === 0) return { lines: 0, files: 0, perFile: [] };

  let totalLines = 0;
  let totalFiles = 0;
  const perFile: Array<{ file: string; count: number }> = [];

  for (const relPath of files) {
    let content: string;
    try {
      content = fs.readFileSync(path.join(cwd, relPath), 'utf-8');
    } catch {
      continue;
    }

    const commentSyntax = skipComments ? commentSyntaxFor(relPath) : null;
    let fileCount = 0;
    for (const rawLine of content.split('\n')) {
      if (commentSyntax && isCommentLine(rawLine, commentSyntax)) continue;
      let matched = false;
      for (const re of compiled) {
        // Reset lastIndex on `g` flag patterns to avoid stateful skips.
        re.lastIndex = 0;
        if (re.test(rawLine)) {
          matched = true;
          break;
        }
      }
      if (matched) fileCount++;
    }
    if (fileCount > 0) {
      totalFiles++;
      totalLines += fileCount;
      if (topN > 0) perFile.push({ file: relPath, count: fileCount });
    }
  }

  let topOffenders: Array<{ file: string; count: number }> = [];
  if (topN > 0) {
    perFile.sort((a, b) => b.count - a.count);
    topOffenders = perFile.slice(0, topN);
  }

  return {
    lines: mode === 'lines' ? totalLines : totalFiles,
    files: totalFiles,
    perFile: topOffenders,
  };
}

function compilePatterns(patterns: RegExp[] | string[]): RegExp[] {
  const out: RegExp[] = [];
  for (const p of patterns) {
    if (p instanceof RegExp) {
      out.push(p);
    } else if (typeof p === 'string' && p.length > 0) {
      try {
        out.push(new RegExp(p));
      } catch {
        // Skip un-compilable patterns rather than throwing — matches
        // grep's behaviour of warning and continuing.
      }
    }
  }
  return out;
}

type CommentSyntax = 'slash' | 'hash' | 'none';

function commentSyntaxFor(relPath: string): CommentSyntax {
  const ext = path.extname(relPath).toLowerCase();
  switch (ext) {
    case '.ts':
    case '.tsx':
    case '.js':
    case '.jsx':
    case '.mjs':
    case '.cjs':
    case '.go':
    case '.rs':
    case '.java':
    case '.kt':
    case '.kts':
    case '.cs':
    case '.cpp':
    case '.cxx':
    case '.cc':
    case '.c':
    case '.h':
    case '.hpp':
    case '.swift':
    case '.scala':
      return 'slash';
    case '.py':
    case '.rb':
    case '.sh':
    case '.bash':
    case '.zsh':
    case '.yml':
    case '.yaml':
    case '.toml':
    case '.r':
      return 'hash';
    default:
      return 'none';
  }
}

function isCommentLine(rawLine: string, syntax: CommentSyntax): boolean {
  if (syntax === 'none') return false;
  const trimmed = rawLine.trimStart();
  if (!trimmed) return false;
  if (syntax === 'slash') {
    return trimmed.startsWith('//') || trimmed.startsWith('/*') || trimmed.startsWith('*');
  }
  return trimmed.startsWith('#');
}

// ─── Re-exports for test convenience ────────────────────────────────────────

/** Surface the pack-aware `sourceExtensions` for a given packId. Used
 *  when callers want to walk one pack's files but bypass the registry. */
export function packSourceExtensions(packId: LanguageId): string[] {
  return getLanguage(packId)?.sourceExtensions ?? [];
}
